// GENERATED by //spec:gen_dynafn from the pinned legend-engine's dynafunction registries -- do not edit.
// Regenerate: bazel run //:update_generated. The platform's decisions are DynaFnDecisions.java's.
package com.legend.builtin;

import java.util.EnumSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * THE ENGINE'S DYNAFUNCTION REGISTRY, as data: every operator name a relational
 * mapping expression may use ({@code hash(col)}, {@code isDistinct(a, b)},
 * {@code concat(…)}), read from the pinned legend-engine checkout's SQL rendering
 * registries — {@code dynaFnToSql('<name>', …)} in {@code extensionDefaults.pure}
 * and every dialect extension — plus the engine's relational type-inference map
 * ({@code getDynaFunctionTypeInferenceMap}, relationalExtension.pure; some names
 * exist only there). Generated whole by {@code DynaFnGenerator}; how THIS platform
 * resolves each name is {@link DynaFnDecisions}' decision, written by hand:
 * <ul>
 *   <li>{@link Resolution#PURE}: passes through to the Pure native(s) the row's
 *       {@link #fqns()} name — the engine's operator IS pure's function;</li>
 *   <li>{@link Resolution#SHIM}: an engine-only operator with no pure signature
 *       (or a shape pure's differs from) — its {@link Pure.Lite} identity;</li>
 *   <li>{@link Resolution#TRANSLATED}: the mapping translator ({@code RelOpTranslator})
 *       rewrites the call into pure's own spelling and NOTHING passes through — a
 *       shape no arm rewrites is an error;</li>
 *   <li>{@link Resolution#UNSUPPORTED}: registered by the engine, handled by nothing
 *       here yet — a mapping using it fails LOUD naming the operator.</li>
 * </ul>
 * A PURE name may ALSO carry a translator arm for the engine's extra shape
 * ({@code and}/{@code or} with more than two operands, {@code parseDate} with a
 * format): {@code DynaFnArms.ARMS} lists every name with an arm, TRANSLATED or PURE.
 * Never a name set anywhere else: {@link #of(String)} is the one lookup.
 */
public enum DynaFn {
    ABS("abs", Inference.MAPPED, Dialect.DEFAULT),
    ACOS("acos", Inference.MAPPED, Dialect.DEFAULT),
    ADD("add", Inference.MAPPED, Dialect.DEFAULT),
    ADJUST("adjust", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    ALL_OF("allOf", Inference.MAPPED, Dialect.DEFAULT),
    AND("and", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    ANY_OF("anyOf", Inference.MAPPED, Dialect.DEFAULT),
    ARRAY_APPEND("array_append", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_CONCATENATE("array_concatenate", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_CONTAINS("array_contains", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_DISTINCT("array_distinct", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_DROP("array_drop", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_FIRST("array_first", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_FLATTEN("array_flatten", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_INIT("array_init", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_LAST("array_last", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_MAX("array_max", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_MIN("array_min", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_POSITION("array_position", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_REVERSE("array_reverse", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_SIZE("array_size", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_SLICE("array_slice", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_SORT("array_sort", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_SUM("array_sum", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_TAIL("array_tail", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_TAKE("array_take", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ARRAY_TO_STRING("array_to_string", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    ASCII("ascii", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    ASIN("asin", Inference.MAPPED, Dialect.DEFAULT),
    ATAN("atan", Inference.MAPPED, Dialect.DEFAULT),
    ATAN2("atan2", Inference.MAPPED, Dialect.DEFAULT, Dialect.MEMSQL, Dialect.SQLSERVER, Dialect.SYBASE),
    AVERAGE("average", Inference.MAPPED, Dialect.DEFAULT),
    AVERAGE_RANK("averageRank", Inference.MAPPED, Dialect.DEFAULT),
    BETWEEN("between", Inference.MAPPED),
    BIT_AND("bitAnd", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    BIT_NOT("bitNot", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    BIT_OR("bitOr", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    BIT_SHIFT_LEFT("bitShiftLeft", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    BIT_SHIFT_RIGHT("bitShiftRight", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    BIT_XOR("bitXor", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    BOOLAND("booland", Inference.MAPPED, Dialect.BIGQUERY, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    BOOLOR("boolor", Inference.MAPPED, Dialect.BIGQUERY, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    CASE("case", Inference.MAPPED),
    CAST("cast", Inference.MAPPED, Dialect.DEFAULT),
    CAST_BOOLEAN("castBoolean", Inference.NONE, Dialect.DUCKDB),
    CBRT("cbrt", Inference.MAPPED, Dialect.DEFAULT, Dialect.ORACLE),
    CEILING("ceiling", Inference.MAPPED, Dialect.DEFAULT, Dialect.ORACLE, Dialect.SNOWFLAKE),
    CHAR("char", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DB2, Dialect.DEFAULT, Dialect.H2, Dialect.MEMSQL, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ),
    CHR("chr", Inference.NONE, Dialect.DUCKDB),
    COALESCE("coalesce", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    CONCAT("concat", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    CONTAINS("contains", Inference.MAPPED, Dialect.DEFAULT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SYBASEIQ),
    CONVERT_DATE("convertDate", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    CONVERT_DATE_TIME("convertDateTime", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    CONVERT_TIME_ZONE("convertTimeZone", Inference.NONE, Dialect.H2, Dialect.MEMSQL, Dialect.SNOWFLAKE),
    CONVERT_VARCHAR128("convertVarchar128", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    CORR("corr", Inference.MAPPED, Dialect.DEFAULT),
    COS("cos", Inference.MAPPED, Dialect.DEFAULT),
    COSH("cosh", Inference.MAPPED, Dialect.DEFAULT),
    COT("cot", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DEFAULT, Dialect.TRINO),
    COUNT("count", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    COVAR_POPULATION("covarPopulation", Inference.MAPPED, Dialect.DEFAULT),
    COVAR_SAMPLE("covarSample", Inference.MAPPED, Dialect.DEFAULT),
    CUMULATIVE_DISTRIBUTION("cumulativeDistribution", Inference.NONE, Dialect.DEFAULT),
    CURRENT_USER_ID("currentUserId", Inference.NONE, Dialect.DEFAULT, Dialect.ORACLE, Dialect.SNOWFLAKE),
    DATE("date", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    DATE_DIFF("dateDiff", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    DATE_PART("datePart", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    DAY_OF_MWEEK("dayOfMWeek", Inference.MAPPED),
    DAY_OF_MONTH("dayOfMonth", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    DAY_OF_WEEK("dayOfWeek", Inference.NONE, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    DAY_OF_WEEK_NUMBER("dayOfWeekNumber", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    DAY_OF_YEAR("dayOfYear", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    DECODE_BASE64("decodeBase64", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SQLSERVER),
    DENSE_RANK("denseRank", Inference.MAPPED, Dialect.DEFAULT),
    DISTINCT("distinct", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    DIVIDE("divide", Inference.MAPPED, Dialect.DEFAULT),
    DIVIDE_ROUND("divideRound", Inference.NONE, Dialect.DEFAULT),
    ENCODE_BASE64("encodeBase64", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SQLSERVER),
    ENDS_WITH("endsWith", Inference.MAPPED, Dialect.DEFAULT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SYBASEIQ),
    EQUAL("equal", Inference.MAPPED, Dialect.DEFAULT),
    EXISTS("exists", Inference.MAPPED, Dialect.DEFAULT),
    EXP("exp", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    EXTRACT_FROM_SEMI_STRUCTURED("extractFromSemiStructured", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.POSTGRES, Dialect.SNOWFLAKE),
    FIRST("first", Inference.NONE, Dialect.DEFAULT, Dialect.DUCKDB),
    FIRST_DAY_OF_MONTH("firstDayOfMonth", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    FIRST_DAY_OF_QUARTER("firstDayOfQuarter", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    FIRST_DAY_OF_THIS_MONTH("firstDayOfThisMonth", Inference.MAPPED, Dialect.BIGQUERY, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    FIRST_DAY_OF_THIS_QUARTER("firstDayOfThisQuarter", Inference.MAPPED, Dialect.BIGQUERY, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    FIRST_DAY_OF_THIS_YEAR("firstDayOfThisYear", Inference.MAPPED, Dialect.BIGQUERY, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    FIRST_DAY_OF_WEEK("firstDayOfWeek", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    FIRST_DAY_OF_YEAR("firstDayOfYear", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    FIRST_HOUR_OF_DAY("firstHourOfDay", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASEIQ, Dialect.TRINO),
    FIRST_MILLISECOND_OF_SECOND("firstMillisecondOfSecond", Inference.MAPPED, Dialect.BIGQUERY, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASEIQ, Dialect.TRINO),
    FIRST_MINUTE_OF_HOUR("firstMinuteOfHour", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASEIQ, Dialect.TRINO),
    FIRST_SECOND_OF_MINUTE("firstSecondOfMinute", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASEIQ, Dialect.TRINO),
    FLOOR("floor", Inference.MAPPED, Dialect.DEFAULT, Dialect.MEMSQL),
    FORMAT_DATE("formatDate", Inference.NONE, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    GENERATE_GUID("generateGuid", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.POSTGRES, Dialect.SNOWFLAKE, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ),
    GREATER_THAN("greaterThan", Inference.MAPPED, Dialect.DEFAULT),
    GREATER_THAN_EQUAL("greaterThanEqual", Inference.MAPPED, Dialect.DEFAULT),
    GREATEST("greatest", Inference.MAPPED, Dialect.DEFAULT, Dialect.SYBASE, Dialect.SYBASEIQ),
    GROUP("group", Inference.MAPPED, Dialect.DEFAULT),
    HASH_AGG("hashAgg", Inference.NONE, Dialect.SNOWFLAKE),
    HASH_CODE("hashCode", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    HOUR("hour", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.COMPOSITE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    IF("if", Inference.MAPPED, Dialect.DEFAULT),
    IN("in", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    INDEX_OF("indexOf", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    IS_ALPHA_NUMERIC("isAlphaNumeric", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ),
    IS_DISTINCT("isDistinct", Inference.NONE, Dialect.DEFAULT),
    IS_EMPTY("isEmpty", Inference.MAPPED, Dialect.DEFAULT, Dialect.ORACLE, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ),
    IS_NOT_EMPTY("isNotEmpty", Inference.MAPPED, Dialect.DEFAULT, Dialect.ORACLE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ),
    IS_NOT_NULL("isNotNull", Inference.MAPPED, Dialect.DEFAULT, Dialect.ORACLE, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ),
    IS_NULL("isNull", Inference.MAPPED, Dialect.DEFAULT, Dialect.ORACLE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ),
    IS_NUMERIC("isNumeric", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ),
    JARO_WINKLER_SIMILARITY("jaroWinklerSimilarity", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DUCKDB, Dialect.H2, Dialect.SNOWFLAKE),
    JOIN_STRINGS("joinStrings", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ),
    KEYS("keys", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    LAG("lag", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DEFAULT),
    LAST("last", Inference.NONE, Dialect.DEFAULT, Dialect.DUCKDB),
    LEAD("lead", Inference.NONE, Dialect.DEFAULT),
    LEAST("least", Inference.MAPPED, Dialect.DEFAULT, Dialect.SYBASE, Dialect.SYBASEIQ),
    LEFT("left", Inference.MAPPED, Dialect.DB2, Dialect.DEFAULT, Dialect.MEMSQL, Dialect.ORACLE, Dialect.PRESTO, Dialect.SPANNER, Dialect.TRINO),
    LENGTH("length", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.COMPOSITE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    LESS_THAN("lessThan", Inference.MAPPED, Dialect.DEFAULT),
    LESS_THAN_EQUAL("lessThanEqual", Inference.MAPPED, Dialect.DEFAULT),
    LEVENSHTEIN_DISTANCE("levenshteinDistance", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.SNOWFLAKE),
    LOG("log", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DEFAULT, Dialect.SPANNER, Dialect.SQLSERVER, Dialect.SYBASE),
    LOG10("log10", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DEFAULT, Dialect.ORACLE, Dialect.POSTGRES, Dialect.REDSHIFT, Dialect.SNOWFLAKE),
    LPAD("lpad", Inference.MAPPED, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.MEMSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.TRINO),
    LTRIM("ltrim", Inference.MAPPED, Dialect.DEFAULT),
    MAP_CONCATENATE("mapConcatenate", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    MATCHES("matches", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    MAX("max", Inference.MAPPED, Dialect.DEFAULT),
    MAX_BY("maxBy", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    MD5("md5", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DB2, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.H2, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    MEDIAN("median", Inference.MAPPED, Dialect.DEFAULT),
    MIN("min", Inference.MAPPED, Dialect.DEFAULT),
    MIN_BY("minBy", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    MINUS("minus", Inference.MAPPED, Dialect.DEFAULT),
    MINUTE("minute", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    MOD("mod", Inference.MAPPED, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.SQLSERVER, Dialect.SYBASE),
    MODE("mode", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DEFAULT),
    MONTH("month", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    MONTH_NAME("monthName", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    MONTH_NUMBER("monthNumber", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    MOST_RECENT_DAY_OF_WEEK("mostRecentDayOfWeek", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    NOT("not", Inference.MAPPED),
    NOT_EQUAL("notEqual", Inference.MAPPED, Dialect.DEFAULT),
    NOT_EQUAL_ANSI("notEqualAnsi", Inference.MAPPED, Dialect.DEFAULT),
    NOW("now", Inference.NONE, Dialect.BIGQUERY, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    NTH("nth", Inference.NONE, Dialect.DEFAULT),
    NTILE("ntile", Inference.NONE, Dialect.DEFAULT),
    NULL_SAFE_EQUAL("nullSafeEqual", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.POSTGRES, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.TRINO),
    NULL_SAFE_NOT_EQUAL("nullSafeNotEqual", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.POSTGRES, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.TRINO),
    OBJECT_REFERENCE_IN("objectReferenceIn", Inference.NONE, Dialect.DEFAULT),
    OR("or", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    PARSE_BOOLEAN("parseBoolean", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.SNOWFLAKE),
    PARSE_DATE("parseDate", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    PARSE_DECIMAL("parseDecimal", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ),
    PARSE_FLOAT("parseFloat", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.COMPOSITE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    PARSE_INTEGER("parseInteger", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.COMPOSITE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    PARSE_JSON("parseJson", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.ORACLE, Dialect.POSTGRES, Dialect.SNOWFLAKE),
    PERCENT_RANK("percentRank", Inference.NONE, Dialect.DEFAULT),
    PERCENTILE("percentile", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DEFAULT),
    PLUS("plus", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    POSITION("position", Inference.NONE, Dialect.BIGQUERY, Dialect.COMPOSITE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    POW("pow", Inference.NONE, Dialect.DEFAULT, Dialect.SPANNER),
    PREVIOUS_DAY_OF_WEEK("previousDayOfWeek", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    QUARTER("quarter", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    QUARTER_NUMBER("quarterNumber", Inference.MAPPED, Dialect.BIGQUERY, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    RANGE("range", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    RANK("rank", Inference.MAPPED, Dialect.DEFAULT),
    REGEXP_COUNT("regexpCount", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.POSTGRES, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.TRINO),
    REGEXP_EXTRACT("regexpExtract", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.MEMSQL, Dialect.POSTGRES, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.TRINO),
    REGEXP_INDEX_OF("regexpIndexOf", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.MEMSQL, Dialect.POSTGRES, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.TRINO),
    REGEXP_LIKE("regexpLike", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.MEMSQL, Dialect.POSTGRES, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.TRINO),
    REGEXP_REPLACE("regexpReplace", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.MEMSQL, Dialect.POSTGRES, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.TRINO),
    REM("rem", Inference.NONE, Dialect.DEFAULT, Dialect.MEMSQL, Dialect.SYBASE),
    REPEAT_STRING("repeatString", Inference.NONE, Dialect.DEFAULT, Dialect.MEMSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.TRINO),
    REPLACE("replace", Inference.MAPPED, Dialect.DEFAULT),
    REVERSE("reverse", Inference.MAPPED),
    REVERSE_STRING("reverseString", Inference.NONE, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.H2),
    RIGHT("right", Inference.MAPPED, Dialect.DB2, Dialect.DEFAULT, Dialect.MEMSQL, Dialect.ORACLE, Dialect.PRESTO, Dialect.SPANNER, Dialect.TRINO),
    ROUND("round", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.COMPOSITE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    ROW_NUMBER("rowNumber", Inference.MAPPED, Dialect.DEFAULT),
    RPAD("rpad", Inference.MAPPED, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.MEMSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.TRINO),
    RTRIM("rtrim", Inference.MAPPED, Dialect.DEFAULT, Dialect.MEMSQL),
    SECOND("second", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    SHA1("sha1", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DB2, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.H2, Dialect.ORACLE, Dialect.POSTGRES, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    SHA256("sha256", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    SIGN("sign", Inference.MAPPED, Dialect.DEFAULT),
    SIN("sin", Inference.MAPPED, Dialect.DEFAULT),
    SINH("sinh", Inference.MAPPED, Dialect.DEFAULT),
    SIZE("size", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    SPLIT("split", Inference.NONE, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.POSTGRES, Dialect.SNOWFLAKE),
    SPLIT_PART("splitPart", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.H2, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SQLSERVER),
    SQL_FALSE("sqlFalse", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DEFAULT, Dialect.SPANNER),
    SQL_NULL("sqlNull", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    SQL_TRUE("sqlTrue", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DEFAULT, Dialect.SPANNER),
    SQRT("sqrt", Inference.MAPPED, Dialect.DEFAULT),
    STARTS_WITH("startsWith", Inference.MAPPED, Dialect.DEFAULT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SYBASEIQ),
    STD_DEV_POPULATION("stdDevPopulation", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    STD_DEV_SAMPLE("stdDevSample", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    SUB("sub", Inference.MAPPED, Dialect.DEFAULT),
    SUBSTRING("substring", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.COMPOSITE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    SUM("sum", Inference.MAPPED, Dialect.DEFAULT),
    TAN("tan", Inference.MAPPED, Dialect.DEFAULT),
    TANH("tanh", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DEFAULT),
    TIME_BUCKET("timeBucket", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    TIMES("times", Inference.MAPPED, Dialect.DEFAULT),
    TO_DECIMAL("toDecimal", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ),
    TO_FLOAT("toFloat", Inference.NONE, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.H2, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ),
    TO_JSON("toJson", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.POSTGRES, Dialect.SNOWFLAKE),
    TO_LOWER("toLower", Inference.MAPPED, Dialect.DEFAULT),
    TO_ONE("toOne", Inference.MAPPED, Dialect.DEFAULT, Dialect.SPANNER),
    TO_STRING("toString", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    TO_TIMESTAMP("toTimestamp", Inference.NONE, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.SNOWFLAKE, Dialect.SPARKSQL, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    TO_UPPER("toUpper", Inference.MAPPED, Dialect.DEFAULT),
    TO_VARIANT("toVariant", Inference.MAPPED, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.POSTGRES, Dialect.SNOWFLAKE),
    TO_VARIANT_LIST("toVariantList", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.POSTGRES, Dialect.SNOWFLAKE),
    TO_VARIANT_OBJECT("toVariantObject", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.POSTGRES, Dialect.SNOWFLAKE),
    TODAY("today", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    TRIM("trim", Inference.MAPPED, Dialect.DEFAULT, Dialect.SYBASE),
    VALUES("values", Inference.NONE, Dialect.DATABRICKS, Dialect.DUCKDB, Dialect.SNOWFLAKE),
    VARIANCE("variance", Inference.NONE, Dialect.CLICKHOUSE, Dialect.DEFAULT, Dialect.DUCKDB),
    VARIANCE_POPULATION("variancePopulation", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.SQLSERVER),
    VARIANCE_SAMPLE("varianceSample", Inference.MAPPED, Dialect.CLICKHOUSE, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.SQLSERVER),
    VARIANT_TO("variantTo", Inference.NONE, Dialect.DEFAULT, Dialect.DUCKDB, Dialect.POSTGRES),
    WEEK_OF_YEAR("weekOfYear", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO),
    YEAR("year", Inference.MAPPED, Dialect.BIGQUERY, Dialect.CLICKHOUSE, Dialect.DATABRICKS, Dialect.DB2, Dialect.DUCKDB, Dialect.H2, Dialect.MEMSQL, Dialect.ORACLE, Dialect.POSTGRES, Dialect.PRESTO, Dialect.REDSHIFT, Dialect.SNOWFLAKE, Dialect.SPANNER, Dialect.SPARKSQL, Dialect.SQLSERVER, Dialect.SYBASE, Dialect.SYBASEIQ, Dialect.TRINO);

    /** How the platform resolves an engine dynafunction. */
    public enum Resolution { PURE, SHIM, TRANSLATED, UNSUPPORTED }

    /** Whether the engine's relational TYPE-INFERENCE map
     *  ({@code getDynaFunctionTypeInferenceMap} in relationalExtension.pure) has
     *  a rule for the name — the engine's second registry of dynafunction names. */
    public enum Inference { MAPPED, NONE }

    /** The engine dialect extension files that register a name. */
    public enum Dialect { BIGQUERY, CLICKHOUSE, COMPOSITE, DATABRICKS, DB2, DEFAULT, DUCKDB, H2, MEMSQL, ORACLE, POSTGRES, PRESTO, REDSHIFT, SNOWFLAKE, SPANNER, SPARKSQL, SQLSERVER, SYBASE, SYBASEIQ, TRINO }

    private final String name;
    private final Inference inference;
    private final EnumSet<Dialect> dialects;

    DynaFn(String name, Inference inference, Dialect... dialects) {
        this.name = name;
        this.inference = inference;
        this.dialects = EnumSet.noneOf(Dialect.class);
        this.dialects.addAll(List.of(dialects));
    }

    /** Whether the engine's type-inference map has a rule for the name. */
    public Inference inference() {
        return inference;
    }

    /** The engine's spelling of the operator. */
    public String dynaName() {
        return name;
    }

    /** The platform's decision for the name ({@link DynaFnDecisions}; UNSUPPORTED unless it says otherwise). */
    public Resolution resolution() {
        return DynaFnDecisions.resolution(this);
    }

    /** The dialects whose rendering registry declares this name (empty for a
     *  name the engine knows only in its type-inference map). */
    public java.util.Set<Dialect> dialects() {
        return java.util.Collections.unmodifiableSet(dialects);
    }

    /** THE DECLARATIONS this name resolves to: a PURE name's catalog FQNs (the engine
     *  surface's for the name, or the declared residue: {@link DynaFnDecisions}), a SHIM's
     *  one {@link Pure.Lite} FQN; empty for TRANSLATED and UNSUPPORTED. The translator
     *  mints a PURE call carrying these as its candidates, so the typer never resolves a
     *  dynafunction by a bare spelling (untangle 4b.2). */
    public List<String> fqns() {
        return DynaFnDecisions.fqns(this);
    }

    /** The {@link Pure.Lite} identity a SHIM resolves to. */
    public String liteFqn() {
        List<String> fqns = fqns();
        if (resolution() != Resolution.SHIM || fqns.size() != 1) {
            throw new IllegalStateException(name + " is not a SHIM");
        }
        return fqns.get(0);
    }

    private static final Map<String, DynaFn> BY_NAME;

    static {
        Map<String, DynaFn> m = new java.util.HashMap<>();
        for (DynaFn d : values()) {
            m.put(d.name, d);
        }
        BY_NAME = java.util.Collections.unmodifiableMap(new java.util.LinkedHashMap<>(m));
    }

    /** The registry entry for an engine operator name, or empty when the engine
     *  registers no such dynafunction (the name is then a plain Pure function
     *  the mapping expression calls, resolved like any other). */
    public static Optional<DynaFn> of(String dynaName) {
        return Optional.ofNullable(BY_NAME.get(dynaName));
    }

    /** Every member of one resolution kind. */
    public static List<DynaFn> withResolution(Resolution r) {
        return java.util.Arrays.stream(values()).filter(d -> d.resolution() == r).toList();
    }
}
