// THE TESTS' IMPORT CLOSURES (Bazel workplan P3-34): for each test/<name>.test.ts, the files under src/ that its
// relative imports reach (through the test helpers too), written as datacube/test_imports.bzl, which BUILD.bazel
// gives each node_test as its data. Editing one source file re-runs only the tests that import it. The list is the
// generator's, never hand-kept: the committed copy's diff test says to regenerate, and a relative import into this
// package that the generator cannot resolve to a declared file fails it (the sandbox alone would not catch a missed
// TRANSITIVE import: Node resolves a source's own imports from where Bazel copied it, beside every other source).
//
// Usage: test-imports <out.bzl> <package> <file>...  (files by their repository paths, as $(rootpaths) gives them)
import { readFileSync, writeFileSync } from 'node:fs';
import { posix } from 'node:path';

const [out, pkg, ...rest] = process.argv.slice(2);
if (out === undefined || pkg === undefined) throw new Error('usage: test-imports <out.bzl> <package> <file>...');
const files = new Set(rest.flatMap((a) => a.split(' ')).filter((f) => f.length > 0));

// a static import, export-from or import(): a type-only import is counted too (it costs a file, never a miss)
const IMPORT = /(?:\bfrom\s*|\bimport\s*\(?\s*)(['"])(\.{1,2}\/[^'"]+)\1/g;

function imports(file: string): string[] {
  const found: string[] = [];
  // comment lines are prose (a comment may quote an import's shape)
  const code = readFileSync(file, 'utf8').split('\n')
    .filter((line) => !/^\s*(\/\/|\/?\*)/.test(line)).join('\n');
  for (const m of code.matchAll(IMPORT)) {
    const target = posix.normalize(posix.join(posix.dirname(file), m[2]!));
    if (files.has(target)) {
      found.push(target);
    } else if (target.startsWith(`${pkg}/src/`) || target.startsWith(`${pkg}/test/`)) {
      // into src/ or test/, and not a declared .ts file: a list built without it would be wrong
      throw new Error(`${file} imports ${m[2]}, which is no declared file (${target})`);
    }
  }
  return found;
}

const tests = [...files].filter((f) => posix.dirname(f) === `${pkg}/test` && f.endsWith('.test.ts')).sort();
if (tests.length === 0) throw new Error(`no ${pkg}/test/*.test.ts among the inputs`);
const lines = [
  '"""GENERATED by //datacube:test_imports (datacube/tools/test-imports.mts): do not edit; bazel run //datacube:update_generated.',
  '',
  'Each DataCube test by name, and the files under src/ its imports reach: its data (Bazel workplan P3-34)."""',
  '',
  'TEST_IMPORTS = {',
];
for (const test of tests) {
  const seen = new Set<string>();
  const todo = [test];
  while (todo.length > 0) {
    for (const next of imports(todo.pop()!)) {
      if (!seen.has(next)) {
        seen.add(next);
        todo.push(next);
      }
    }
  }
  const src = [...seen].filter((f) => f.startsWith(`${pkg}/src/`)).map((f) => f.slice(pkg.length + 1)).sort();
  const name = posix.basename(test).slice(0, -'.test.ts'.length);
  lines.push(src.length === 0 ? `    "${name}": [],` : `    "${name}": [`, ...src.map((f) => `        "${f}",`));
  if (src.length > 0) lines.push('    ],');
}
lines.push('}', '');
writeFileSync(out, lines.join('\n'));
