// THE TESTS' IMPORT CLOSURES (Bazel workplan P3-34): for each test/<name>.test.ts, the files under src/ that its
// relative imports reach (through the test helpers too), written as datacube/test_imports.bzl, which BUILD.bazel
// gives each node_test as its data. Editing one source file re-runs only the tests that import it; a test that
// imports a file it does not declare fails in the sandbox, and the committed list's diff test says to regenerate.
//
// Usage: test-imports <out.bzl> <package> <file>...  (files by their repository paths, as $(rootpaths) gives them)
import { readFileSync, writeFileSync } from 'node:fs';
import { posix } from 'node:path';

const [out, pkg, ...rest] = process.argv.slice(2);
if (out === undefined || pkg === undefined) throw new Error('usage: test-imports <out.bzl> <package> <file>...');
const files = new Set(rest.flatMap((a) => a.split(' ')).filter((f) => f.length > 0));

// a static import, export-from or import(): a type-only import is counted too (it costs a file, never a miss)
const IMPORT = /(?:\bfrom\s*|\bimport\s*\(?\s*)'(\.{1,2}\/[^']+)'/g;

function imports(file: string): string[] {
  const found: string[] = [];
  for (const m of readFileSync(file, 'utf8').matchAll(IMPORT)) {
    const target = posix.normalize(posix.join(posix.dirname(file), m[1]!));
    if (files.has(target)) found.push(target);
  }
  return found;
}

const tests = [...files].filter((f) => posix.dirname(f) === `${pkg}/test` && f.endsWith('.test.ts')).sort();
if (tests.length === 0) throw new Error(`no ${pkg}/test/*.test.ts among the inputs`);
const lines = [
  '"""GENERATED by //datacube:test_imports (datacube/tools/test-imports.mts): do not edit; bazel run //datacube:update_generated.',
  '',
  'Each DataCube test by name, and the files under src/ its imports reach: its data (Bazel workplan P3-34)."""',
  '',
  'TEST_IMPORTS = {',
];
for (const test of tests) {
  const seen = new Set<string>();
  const todo = [test];
  while (todo.length > 0) {
    for (const next of imports(todo.pop()!)) {
      if (!seen.has(next)) {
        seen.add(next);
        todo.push(next);
      }
    }
  }
  const src = [...seen].filter((f) => f.startsWith(`${pkg}/src/`)).map((f) => f.slice(pkg.length + 1)).sort();
  const name = posix.basename(test).slice(0, -'.test.ts'.length);
  lines.push(src.length === 0 ? `    "${name}": [],` : `    "${name}": [`, ...src.map((f) => `        "${f}",`));
  if (src.length > 0) lines.push('    ],');
}
lines.push('}', '');
writeFileSync(out, lines.join('\n'));
