"""
L0 driver — regenerates the asserted stress corpus from the seed data and the oracle.

  bazel run //core:update_stress_corpus    regenerate the committed artefacts (a Bazel action runs this
                                          program with --out DIR; //:generated diff-tests them)

The generated files are committed. That is deliberate: they are the portable artefact
other engines consume, and a reviewer must be able to read the expectation in the diff.
The write_source_files diff tests keep them honest (Bazel workplan P2-01); the old in-place
write and --check modes are gone.

Nothing is written unless every stage passes: the model resolves, the seed satisfies its
schema and all twelve adversarial properties, and the oracle evaluates every service
without refusing. A refusal is not routed around — it means the corpus contains a case
whose answer we cannot predict, and shipping it would mean asserting whatever the engine
happened to produce.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import battery
import emit
import flat
import functest
import model
import oracle
import query
import seed
import aggregates
import graphs
import combos
import hier
import quarantine
import spread
import stacks
import taxonomy
import tomany
from model import STRESS

DATA_FILE = STRESS / "93-testdata.pure"
SERVICES_FILE = STRESS / "92-services.pure"
FANOUT_FILE = STRESS / "94-fanout-services.pure"
FUNCTEST_FILE = STRESS / "95-function-tests.pure"
EXTERNAL_DATA_FILE = STRESS / "96-external-data.pure"
HIER_FILE = STRESS / "97-hier-execution.pure"
COMBO_FILE = STRESS / "98-combination-execution.pure"

HEADER = """// GENERATED by scripts/corpus/build.py -- do not edit by hand.
//
// Seed data for the stress corpus: {rows} rows across {tables} tables, carrying the
// adversarial properties A1..A12 documented in scripts/corpus/seed.py (orphan and NULL
// foreign keys, zero-child entities, ties, skew, empty-vs-NULL strings, apostrophes and
// a broken two-hop chain). Regenerate with `python3 scripts/corpus/build.py`.
"""

FANOUT_HEADER = """// The fan-out battery. Every ->count() here crosses a to-many association, which the
// original 12 services never did (0 of 530 projection paths). Expectations come from the
// reference evaluator; the zeroes are the point -- see scripts/corpus/battery.py.
//
// GENERATED by scripts/corpus/build.py -- do not edit by hand.
"""

SERVICES_HEADER = """// Stress test queries as portable Service definitions, each carrying a testSuite whose
// expectation was computed by the reference evaluator in scripts/corpus/oracle.py from
// the seed data in 93-testdata.pure -- NOT captured from engine output.
//
// GENERATED by scripts/corpus/build.py -- do not edit by hand. Edit the seed or the
// queries and regenerate, so the expectation can never drift from the data.
"""


def split_services(text: str) -> tuple[str, list[tuple[str, str]]]:
    """(preamble, [(name, body)]) where body runs from `Service x` to its closing brace."""
    marker = "\n###Service\n"
    i = text.index(marker)
    preamble, rest = text[:i], text[i + len(marker):]
    out, cur, buf, depth, started = [], None, [], 0, False
    for line in rest.splitlines():
        if line.startswith("Service ") and cur is None:
            cur, buf, depth, started = line.split()[1], [line], 0, False
        if cur is None:
            continue
        if line is not buf[0]:
            buf.append(line)
        depth += line.count("{") - line.count("}")
        if "{" in line:
            started = True
        if started and depth == 0:
            out.append((cur, "\n".join(buf)))
            cur = None
    if cur is not None:
        raise ValueError(f"unterminated service {cur}")
    return preamble, out


def _expect(c, spec, TABLES):
    """The expectation for a spec, following `mirrors` when the oracle cannot evaluate."""
    src = getattr(spec, "mirrors", None)
    if src is None:
        try:
            return oracle.as_json_rows(c, spec, oracle.evaluate(c, spec, TABLES))
        except (oracle.Fanout, oracle.Unsupported):
            raise
        except Exception as e:
            # An oracle crash used to arrive as a bare TypeError from inside _cmp, naming
            # neither the service nor the generator that produced it -- so finding which of
            # ~4700 specs was at fault meant bisecting the generators by hand.
            raise type(e)(f"{spec.name} (root {spec.root}): {e}") from e
    # For a grouped spec the RESULT aliases are the keys plus the aggregate names, not
    # the projection list -- comparing projections would reject a valid pairing.
    def result_aliases(s):
        if s.graph:
            return sorted(s.graph)          # a tree's top-level keys
        if s.group_by:
            return [*s.group_by, *(n for n, _, _ in s.aggs)]
        return [p.alias for p in s.projections]

    mine, theirs = result_aliases(spec), result_aliases(src)
    if sorted(mine) != sorted(theirs):
        raise SystemExit(
            f"{spec.short} mirrors {src.short} but their projection aliases differ:\n"
            f"  {spec.short}: {sorted(mine)}\n  {src.short}: {sorted(theirs)}")
    rows = oracle.as_json_rows(c, src, oracle.evaluate(c, src, TABLES))
    fn = getattr(spec, "transform", None)
    return [fn(r) for r in rows] if fn else rows


def generate() -> dict[Path, str]:
    c = model.load()
    TABLES = flat.all_tables(c)

    problems = model.check(c)
    if problems:
        raise SystemExit("model does not resolve:\n  " + "\n  ".join(problems[:10]))
    import aggregate
    import expand
    import partition
    problems = ([p for produced, base in flat.EXPANSION_LAYERS
                 for p in expand.check(c, produced, base)]
                + aggregate.check(c, TABLES["TRADE_BY_BOOK"], TABLES)
                + seed.check(c) + flat.check(c, TABLES['TRADE_FLAT'])
                + flat.check_partial(TABLES["TRADE_FLAT_PARTIAL"])
                + partition.check(c, {k: TABLES[k] for k in
                                      ('TRADE_EQ', 'TRADE_RATES', 'TRADE_FX')},
                                  TABLES))
    if problems:
        raise SystemExit("seed is invalid:\n  " + "\n  ".join(problems[:10]))

    specs = query.load()

    out = []
    for spec in specs:
        rows = oracle.evaluate(c, spec, TABLES)      # raises Fanout, never guesses
        expected = oracle.as_json_rows(c, spec, rows)
        nulls = sum(1 for r in expected for v in r.values() if v is None)
        note = (f"{len(expected)} rows x {len(spec.projections)} columns, "
                f"{nulls} NULL cells from orphan/absent foreign keys")
        out.append(emit.service(spec, expected, note))

    services = SERVICES_HEADER + "\n###Service\n" + "\n\n".join(out) + "\n"

    # L2: the two sides of the invariance pair must agree before anything is emitted.
    # If they do not, the fixture is wrong — the denormalization does not carry the same
    # facts — and shipping both would produce two tests that disagree for a reason that
    # has nothing to do with the engine.
    key = lambda rs: sorted(json.dumps(r, sort_keys=True) for r in rs)
    for group in battery.INVARIANCE_GROUPS:
        inv = [(s.short, key(_expect(c, s, TABLES))) for s in group]
        base_name, base = inv[0]
        for name, rows in inv[1:]:
            if rows != base:
                only_a = [r for r in base if r not in rows][:2]
                only_b = [r for r in rows if r not in base][:2]
                raise SystemExit(
                    f"invariance FAILS in the fixture itself "
                    f"({base_name} vs {name}):\n"
                    f"  {base_name}-only: {only_a}\n  {name}-only: {only_b}")

    # Dense services generated FROM the model — they deepen as the model does, rather
    # than needing a new hand-written service per domain.
    seeded_now = {k for k, v in TABLES.items() if v}
    generated = stacks.build(c, seeded_now)
    # Graph-fetch INSTANCES over the same model. battery.py's G0-G3 remain the properties
    # -- nested to-one navigation, a union with an empty leg, the enum that raises on one
    # execution path, %latest -- and these are the shapes those properties should hold
    # over. Four hand-picked roots became sixty ranked ones without a new property being
    # invented, which is the whole point of the split.
    generated += graphs.build(c, seeded_now, TABLES)
    # Aggregate instances over to-many ends whose every parent HAS children -- the
    # non-empty half of the property the F-series pins on the empty half. F6 is what makes
    # the split necessary: it fails a whole service if any one row hits the empty case.
    generated += aggregates.build(c, seeded_now, TABLES)
    # EMPTINESS over to-many ends. aggregates.py can only use the ends where EVERY parent
    # has children, because F6 makes count() return 1 over an empty set and one such row
    # fails the whole service. isEmpty/isNotEmpty are correct there, so these reach the 105
    # ends that count() cannot -- and assert the empty case 299 times rather than avoiding it.
    generated += tomany.build(c, seeded_now, TABLES)
    # One service per subtype of every discriminated taxonomy: the only way a wrong ~filter
    # is visible, since it fails by returning the WHOLE table rather than by erroring.
    generated += taxonomy.build(c, seeded_now, TABLES)
    # STACKED query shapes over those same taxonomies and roots. taxonomy.py gives each
    # subtype one bare projection, which proves its ~filter and nothing else; this stacks a
    # filter, an aggregation, an ordering and a computation on top, and reaches four hops
    # deep on the 45 roots that can navigate at all. The bare services are kept as the
    # control -- a stacked query is only interpretable if a simple one over the same rows
    # passes, and a wrong ~filter is only visible in the simple one.
    import deepstack
    generated += deepstack.build(c, seeded_now, TABLES)
    # Coverage-directed services: chosen by which feature COMBINATIONS they close rather
    # than by walking the model, which is what every generator above does. Runs last
    # because it needs to know what the others already cover.
    # The SAME baseline the scoreboard uses, from one function, so the file and the number
    # cannot describe different corpora. base_specs is everything except these.
    import executed as _executed          # `executed` is a local further down this function
    generated += spread.build(c, seeded_now, _executed.base_specs(c))
    fan = []
    for spec in list(battery.SPECS) + generated:
        expected = _expect(c, spec, TABLES)
        zeros = sum(1 for r in expected for k, v in r.items()
                    if any(p.agg for p in spec.projections if p.alias == k) and v == 0)
        note = (f"{len(expected)} rows; {zeros} of the aggregate cells are ZERO -- an "
                f"entity with no children. COUNT(*) over the outer join would return 1.")
        fan.append(emit.service(spec, expected, note))
    fanout = FANOUT_HEADER + "\n###Service\n" + "\n\n".join(fan) + "\n"
    data = (HEADER.format(rows=sum(len(v) for v in TABLES.values()),
                          tables=len(TABLES))
            + "\n" + emit.data_element(c, TABLES) + "\n")
    external = ("// GENERATED by scripts/corpus/build.py -- do not edit by hand.\n"
                "//\n// Test data for the SECOND store. Kept separate because test data\n"
                "// is bound to a CONNECTION, and the two stores have different ones.\n\n"
                + emit.external_data_element(c, TABLES) + "\n")
    # The hier:: feature domain: runtime, its own ###Data (bound to its own connection),
    # and services for the classes whose every property the ORACLE can resolve. Classes
    # with a property the reader cannot model are excluded by hier.executable(), so a
    # Binding transformer or join chain keeps its class compile-only rather than producing
    # a service whose expectations would have to come from the engine under test.
    hier_specs = hier.specs(c)
    hier_svc = [emit.service(s, _expect(c, s, TABLES),
                             f"{len(s.projections)} columns over the hier:: feature mapping.")
                for s in hier_specs]
    hier_data = "\n\n".join(
        emit.store_data_element(c, TABLES, db, elem)
        for db, (_m, _r, _c, elem) in sorted(hier.BINDINGS.items()))
    # STORE SUBSTITUTION: the substituted store needs its own runtime and its own ###Data,
    # seeded with the SAME rows. `only` names the tables explicitly because both databases
    # declare them and this reader keys table names globally, so every one is attributed to
    # whichever database was read first.
    prod_data = emit.store_data_element(
        c, TABLES, hier.PROD_DB, hier.PROD_DATA,
        only=[n for n in TABLES if TABLES[n] and n.startswith("HIER_ISSUER")])
    hier_text = (hier.runtime_text() + hier.prod_runtime_text() + "\n"
                 + hier_data + "\n\n" + prod_data + "\n\n"
                 + "###Service\n" + "\n\n".join(hier_svc) + "\n")

    # The COMBINATION matrix: mapping features stacked on each other rather than each
    # appearing once. Its pair coverage is asserted by combos.check() before anything is
    # emitted -- a dealing rule that silently misses a pair is the failure this replaces.
    problems = (combos.check() + combos.check_data(c, TABLES)
                + quarantine.check_f24(c, TABLES))
    # RATCHET: a feature that reaches a passing service must not fall back to compile-only.
    # Presence was already ratcheted by density.py, and presence is the number that was
    # misleading -- nine taxonomy entries scored present while being declared once and
    # reached by nothing.
    import executed
    problems += _unreachable_roots(c, generated)
    problems += _id_collisions()
    quarantined = set(quarantine.ENGINE_QUARANTINE) | set(quarantine.HANGS)
    problems += [f"feature no longer executed: {n}" for n in executed.regressions(
        executed.report(c, executed.all_specs(c), quarantined))]
    if problems:
        raise SystemExit("combination matrix is incomplete:\n  " + "\n  ".join(problems))
    combo_specs = combos.specs(c)
    combo_svc = [emit.service(s, _expect(c, s, TABLES),
                              f"{len(s.projections) - 1} combination cells, each a distinct "
                              f"(reach, transform, nullability, host) stacking.")
                 for s in combo_specs]
    combo_text = (combos.runtime_text() + "\n"
                  + emit.store_data_element(c, TABLES, combos.DB, combos.DATA) + "\n\n"
                  + "###Service\n" + "\n\n".join(combo_svc) + "\n")

    return {DATA_FILE: data, SERVICES_FILE: services, FANOUT_FILE: fanout,
            FUNCTEST_FILE: functest.render(c, TABLES),
            EXTERNAL_DATA_FILE: external, HIER_FILE: hier_text,
            COMBO_FILE: combo_text}


def _id_collisions() -> list[str]:
    """Set-implementation ids that collide inside one mapping closure, and filter names that
    collide at all.

    Both are GLOBAL namespaces and both fail the whole corpus rather than one service:

        Duplicated class mappings found with ID 'payBookTransfer' in mapping
        'stress::AllMapping'

    which is a compile error, so nothing runs and no test reports. It cost a full suite run
    to discover that a new taxonomy had reused another's three-letter tag -- refdata builds
    both the set id and the filter name from it, so one collision produces two.

    Set ids are checked per closure because two FIXTURE mappings legitimately share `base`;
    they are never included together. Filter names are checked globally because every filter
    in this corpus is declared in the one store.
    """
    import collections
    import re

    import executed

    src = "".join(p.read_text() for p in model.stress_sources())
    out = []

    counts = collections.Counter(re.findall(r"Filter (\w+)\(", src))
    out += [f"filter name {n!r} is declared {k} times; the store keeps one"
            for n, k in sorted(counts.items()) if k > 1]

    # mapping -> the set ids it declares
    by_mapping: dict[str, list[str]] = {}
    heads = list(re.finditer(r"^Mapping\s+([\w:]+)", src, re.M))
    for i, h in enumerate(heads):
        end = heads[i + 1].start() if i + 1 < len(heads) else len(src)
        # A class mapping DECLARES a set id -- `Class[id]: Relational`. A property mapping
        # merely NAMES one as its target -- `prop[id]: [store]@Join` -- and 72 taxonomies
        # pointing at one shared `posBook` are not 72 declarations of it. Requiring the
        # `: Relational` tail is what tells them apart.
        by_mapping[h.group(1)] = re.findall(
            r"^\s*\*?[\w:]+\[(\w+)\](?:\s+extends\s*\[\w+\])?\s*:\s*Relational",
            src[h.start():end], re.M)
    for name, included in sorted(executed.include_closure().items()):
        seen = collections.Counter(
            sid for m in included for sid in by_mapping.get(m, ()))
        out += [f"set id {sid!r} is declared {k} times within {name}"
                for sid, k in sorted(seen.items()) if k > 1]
    return out


def _unreachable_roots(c, specs) -> list[str]:
    """Every class a service roots at must be reachable from the mapping it names.

    A class can be perfectly declared, perfectly mapped and still unreachable, because
    reachability is a property of the ALL-MAPPING's include list rather than of the class.
    `timeseries::TimeSeries` was mapped correctly in its own mapping and left out of
    stress::AllMapping, and nothing said so: model.check passed, the build wrote 961
    services, and the failure arrived an hour later as an Assert inside plan generation --
    "Error mapping not found for class TimeSeries" -- which killed the whole batch it was in
    rather than the one service that caused it.

    The insert that should have added the include had been suppressed by a guard reading
    `if "include marketdata::" not in text`, and it was in the text: for a DIFFERENT mapping
    in the same package. So the check here is on the thing that actually matters -- can the
    named mapping resolve this class -- and not on whether some edit looks like it happened.
    """
    import executed

    closure = executed.include_closure()
    # Parsed rather than taken from c.declared_in, which keeps ONE mapping per class: four
    # services name an alternative mapping of trading::Trade or hier::Issuer, and against a
    # one-mapping-per-class map every one of them looks unreachable.
    mapped_by = executed.class_mappings()
    out = []
    for spec in specs:
        named = spec.mapping or "stress::AllMapping"
        reach = closure.get(named)
        # A mapping the closure does not know is an inline or generated one; nothing to say.
        if reach is None or spec.root not in mapped_by:
            continue
        if not (mapped_by[spec.root] & reach):
            out.append(f"{spec.name.split('::')[-1]} roots at {spec.root}, which "
                       f"{named} cannot resolve -- it is mapped only in "
                       f"{', '.join(sorted(mapped_by[spec.root]))}. Add the include.")
    return out


def main() -> None:
    if "--dense" in sys.argv:
        model.DENSE_DIR = Path(sys.argv[sys.argv.index("--dense") + 1])
    if "--out" not in sys.argv:
        raise SystemExit("build.py runs as a Bazel action (--out DIR): regenerate with "
                         "`bazel run //core:update_stress_corpus`")
    # write every generated file into the action's output directory, nothing else; the committed
    # copies are compared by the write_source_files diff test (//:generated), not here
    out = Path(sys.argv[sys.argv.index("--out") + 1])
    out.mkdir(parents=True, exist_ok=True)
    for path, text in generate().items():
        (out / path.name).write_text(text, encoding="utf-8", newline="\n")

if __name__ == "__main__":
    main()
