"""
Generates a FEATURE-DENSE mapping that is semantically identical to the flat one.

94% of the corpus's 397 class mappings are `~mainTable` plus a list of direct columns. The
features that make a Legend mapping interesting -- scopes, set ids, inheritance, includes,
store substitution -- are absent, so nothing has ever tested them and no finding could have
come from them.

The obstacle to fixing that is the ORACLE. Features that change values -- dynafunctions, join
chains, `~distinct`, `~filter` -- need oracle.py to compute the same thing a different way,
which is real work and a real risk of asserting the generator's opinion rather than the
truth.

So this starts with the half that needs NO oracle change: features that restructure a mapping
without altering what it means.

    scope([db]T)( ... )        purely syntactic grouping; the composer flattens it back
    *Class[id] / Class[id]     set ids and the root marker
    extends [parentId]         property mappings inherited from another set
    ~primaryKey ( ... )        declares what was already implied by the table's PK
    include / substitution     the same mappings, reached through another mapping

Every one of those is a different SPELLING of the flat mapping beside it. That makes the
assertion free and unusually strong: run the same query through both mappings and the results
must be IDENTICAL. No expectation is computed, so no expectation can be wrong -- and the
corpus already has this mechanism, INVARIANCE_GROUPS in battery.py, built for exactly this
shape of claim.

What this deliberately does NOT do is generate a dynafunction or a join chain. Those change
the answer, the oracle cannot yet follow them, and generating them here would produce tests
whose expectations came from the engine being tested. That is phase two, and it is gated on
oracle support rather than on syntax -- the syntax is already verified in
scripts/corpus/verified/.
"""
from __future__ import annotations

import model

HEADER = """// GENERATED by scripts/corpus/dense_mapping.py -- do not edit by hand.
//
// A SECOND mapping of classes already mapped flatly elsewhere, expressing the same thing
// with the features the flat mapping does not use: scope blocks, set ids, extends, an
// explicit ~primaryKey, and an include of the flat mapping it shadows.
//
// Semantically IDENTICAL by construction. That is the assertion: a query answered through
// this mapping must return exactly what the flat mapping returns, so the invariance holds
// with no computed expectation on either side. A divergence is a defect in how one of the
// two spellings is interpreted -- which is precisely the class of defect the corpus has
// never been able to look for, because it only ever had one spelling.
"""


def _identifier(c: model.Corpus, cls: str) -> str | None:
    table = c.tables.get(c.main_table.get(cls, ""))
    if table is None or not table.pk:
        return None
    return next((p for p, col in c.columns.get(cls, {}).items() if col == table.pk[0]), None)


# THE SEED: the classes this generator re-maps, in order (the order fixes each set id). It used
# to rank EVERY class in the corpus and take the first 60, so each new stress file
# whose classes sorted early displaced old picks and churned the whole file (50 of 60 classes
# had moved by 2026-10-02). These are its picks as of the file it wrote on 2026-08-14
# (b88fbe90f). Widening the mapping is a deliberate edit to this list; a class that stops
# qualifying fails the build rather than silently dropping out.
SEED_CLASSES = (
    "accounting::AccountingRule",
    "accounting::AccrualSchedule",
    "accounting::AuditTrail",
    "accounting::BalanceSheet",
    "accounting::CostAllocation",
    "accounting::GeneralLedgerAccount",
    "accounting::IncomeStatement",
    "accounting::JournalEntry",
    "accounting::SubledgerEntry",
    "accounting::TrialBalance",
    "clearing::CCPMarginCall",
    "clearing::ClearedTrade",
    "clearing::ClearingFee",
    "clearing::ClearingHouse",
    "clearing::ClearingMember",
    "clearing::DefaultFund",
    "clearing::NovationRequest",
    "clearing::PortfolioReconciliation",
    "clearing::PositionTransfer",
    "clearing::TradeCompression",
    "collateral::CollateralAgreement",
    "collateral::CollateralBalance",
    "collateral::CollateralDispute",
    "collateral::CollateralPosting",
    "collateral::CollateralSubstitution",
    "collateral::EligibilityRule",
    "collateral::HaircutSchedule",
    "collateral::InitialMargin",
    "collateral::MarginCall",
    "collateral::VariationMargin",
    "counterparty::Account",
    "counterparty::Agreement",
    "counterparty::BeneficialOwner",
    "counterparty::Classification",
    "counterparty::Contact",
    "counterparty::Counterparty",
    "counterparty::CounterpartyLimit",
    "counterparty::CreditRating",
    "counterparty::KYCRecord",
    "counterparty::RatingVersion",
    "counterparty::SanctionsCheck",
    "external::LegalEntity",
    "funding::CashFlow",
    "funding::CashForecast",
    "funding::FundingCost",
    "funding::FundingRate",
    "funding::FundingRequirement",
    "funding::IntercompanyLoan",
    "funding::LiquidityPool",
    "funding::RepoTrade",
    "funding::SecuritiesLoan",
    "funding::TreasuryTransaction",
    "marketdata::BenchmarkRate",
    "marketdata::CorporateSpread",
    "marketdata::CreditSpread",
    "marketdata::DividendForecast",
    "marketdata::FxRate",
    "marketdata::ImpliedVolPoint",
    "marketdata::MarketDataSnapshot",
    "marketdata::MarketQuote",
)


def candidates(c: model.Corpus, seeded: set[str]) -> list[str]:
    """The seed classes, each checked to still be worth re-mapping: seeded, single-table,
    with enough columns to be worth splitting across scope blocks."""
    out = []
    for cls in SEED_CLASSES:
        tbl = c.main_table.get(cls)
        if tbl is None or tbl not in seeded or cls in c.views:
            raise SystemExit(f"dense_mapping seed {cls} is no longer a seeded, mapped class")
        cols = c.columns.get(cls, {})
        table = c.tables.get(tbl)
        # Only columns that really exist on the main table -- a property mapped through a
        # join is not something this generator can restate.
        if (table is None or not table.pk or len(cols) < 4 or _identifier(c, cls) is None
                or not all(col in table.columns for col in cols.values())):
            raise SystemExit(f"dense_mapping seed {cls} no longer qualifies for re-mapping")
        out.append(cls)
    return out


def _db_of(c: model.Corpus, table: str) -> str:
    return getattr(c.tables[table], "database", "store::DB")


def build(c: model.Corpus, seeded: set[str]) -> str:
    """The dense mapping, as .pure text."""
    classes = candidates(c, seeded)
    lines = [HEADER, "###Mapping", "Mapping stress::DenseMapping", "("]

    for n, cls in enumerate(classes):
        tbl = c.main_table[cls]
        table = c.tables[tbl]
        db = _db_of(c, tbl)
        cols = c.columns[cls]
        ident = _identifier(c, cls)
        short = cls.split("::")[-1]

        # Split the property mappings into two scope blocks. One scope would prove the
        # keyword parses; two proves the composer really is flattening them back into one
        # set rather than producing two.
        props = [p for p in sorted(cols) if p != ident]
        half = max(1, len(props) // 2)
        first, second = props[:half], props[half:]

        setid = f"d{n}_{short.lower()}"
        lines.append(f"   *{cls}[{setid}]: Relational")
        lines.append("   {")
        lines.append(f"      ~primaryKey ( [{db}]{tbl}.{table.pk[0]} )")
        lines.append(f"      ~mainTable [{db}]{tbl}")
        lines.append(f"      {ident}: [{db}]{tbl}.{cols[ident]},")
        lines.append(f"      scope([{db}]{tbl})")
        lines.append("      (")
        lines.append(",\n".join(f"         {p}: {cols[p]}" for p in first))
        lines.append("      )" + ("," if second else ""))
        if second:
            # The db-pointer-only form of scope, so BOTH arms of the rule are exercised.
            lines.append(f"      scope([{db}])")
            lines.append("      (")
            lines.append(",\n".join(f"         {p}: {tbl}.{cols[p]}" for p in second))
            lines.append("      )")
        lines.append("   }")
        lines.append("")

    lines.append(")")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import flat

    c = model.load()
    tables = flat.all_tables(c)
    seeded = {t for t, rows in tables.items() if rows}
    text = build(c, seeded)
    n = text.count(": Relational")
    print(f"dense mapping: {n} class mappings, {len(text.splitlines())} lines")
    print(f"  scope blocks : {text.count('scope(')}")
    print(f"  set ids      : {text.count('[d')}")
    print(f"  ~primaryKey  : {text.count('~primaryKey')}")
