"""
Generates a Database that flexes the STORE features the corpus has never used.

The model has 184 joins and every one of them is a single-column equality. It has one View,
one Filter, no Schema, no TabularFunction, no MultiGrainFilter, and no join that uses more
than one column or anything other than `=`. That is not a model of a relational store; it is
a model of foreign keys.

This adds a Database that `include`s the existing one and declares new store objects over the
SAME tables. Including rather than duplicating matters: the tables already have seeded rows,
so anything mapped over these objects can actually be executed rather than merely compiled,
and no existing mapping changes meaning because nothing existing is touched.

Everything here is derived from the model -- real tables, real columns, real types -- so a
column rename breaks the generator loudly instead of producing a Database that compiles
against tables that no longer have those columns.

Every construct's spelling comes from scripts/corpus/verified/store.md, where it was run
through the engine before being written down. Two rules from that survey are load-bearing
here and are easy to get wrong:

  * `and` and `or` have EQUAL precedence and are right-associative, so `A and B or C` parses
    as `A and (B or C)`. Every mixed condition below is parenthesised deliberately.
  * a View's directive order is `~filter` then `~groupBy` then `~distinct` -- the OPPOSITE
    of a class mapping's `~filter ~distinct ~groupBy`. Both are parse errors when wrong.
"""
from __future__ import annotations

import model

DB = "stress::DenseDB"
BASE = "store::DB"

# THE SEED: the tables this generator chooses among. It used to choose among EVERY table in the
# corpus, so adding any stress file whose table sorts first (ACCESS_ENTITLEMENT did) silently
# every object here and churned the file. These are its picks as of the
# file it wrote on 2026-08-14 (6718aae22); widening the store is a deliberate edit to this list.
SEED_TABLES = ("ACCOUNT", "ACCOUNTING_RULE", "ACCRUAL_ENTRY", "ACCRUAL_SCHEDULE")


def _seed(c: model.Corpus) -> list[str]:
    missing = [t for t in SEED_TABLES if t not in c.tables or t in c.views]
    if missing:
        raise SystemExit(f"dense_store seed tables no longer in the model: {missing}")
    return sorted(SEED_TABLES)


def _tables_with(c: model.Corpus, kind: str, minimum: int = 1) -> list[str]:
    """Seed tables having at least `minimum` columns of `kind`, deterministically ordered."""
    out = []
    for name in _seed(c):
        t = c.tables[name]
        if sum(1 for col in t.columns.values() if col.kind == kind) >= minimum:
            out.append(name)
    return out


def _cols(c: model.Corpus, table: str, kind: str) -> list[str]:
    return sorted(col.name for col in c.tables[table].columns.values() if col.kind == kind)


def _shared_columns(c: model.Corpus, a: str, b: str) -> list[str]:
    return sorted(set(c.tables[a].columns) & set(c.tables[b].columns))


def build(c: model.Corpus) -> str:
    L = [
        "// GENERATED by scripts/corpus/dense_store.py -- do not edit by hand.",
        "//",
        "// Store features the base Database does not use. It INCLUDES store::DB rather than",
        "// redeclaring anything, so these objects sit over tables that already carry seeded",
        "// rows -- executable, not merely compilable -- and no existing mapping is touched.",
        "//",
        "// Spellings verified in scripts/corpus/verified/store.md. Two rules matter here:",
        "// `and`/`or` are equal-precedence and right-associative (so mixed conditions are",
        "// parenthesised), and a View orders its directives ~filter ~groupBy ~distinct --",
        "// the opposite of a class mapping. Both are parse errors when wrong.",
        "",
        "###Relational",
        f"Database {DB}",
        "(",
        f"   include {BASE}",
        "",
    ]

    # ---- a Schema, with its own tables and a view over them ------------------------------
    L += [
        "   // A Schema, so a schema-qualified table reference is resolved somewhere in the corpus",
        "   // (the base model's tables sit in the default schema).",
        "   Schema analytics",
        "   (",
        "      Table DESK_SUMMARY",
        "      (",
        "         DESK_ID VARCHAR(64) PRIMARY KEY,",
        "         AS_OF DATE PRIMARY KEY,",
        "         HEADCOUNT INTEGER,",
        "         GROSS_NOTIONAL DOUBLE,",
        "         LABEL VARCHAR(128)",
        "      )",
        "      Table DESK_LIMIT",
        "      (",
        "         DESK_ID VARCHAR(64) PRIMARY KEY,",
        "         LIMIT_KIND VARCHAR(32) PRIMARY KEY,",
        "         LIMIT_VALUE DOUBLE NOT NULL",
        "      )",
        "      // A TabularFunction: its parenthesised body is a COLUMN SCHEMA, not an",
        "      // argument list -- the same columnDefinition rule a Table uses.",
        "      TabularFunction DESK_ROLLUP",
        "      (",
        "         DESK_ID VARCHAR(64) NOT NULL,",
        "         TOTAL DOUBLE",
        "      )",
        "   )",
        "",
    ]

    joins: list[str] = []

    # ---- multi-column join, over real shared columns -------------------------------------
    pair = None
    names = _seed(c)
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            shared = [s for s in _shared_columns(c, a, b) if s not in c.tables[a].pk]
            if len(shared) >= 2:
                pair = (a, b, shared[:2])
                break
        if pair:
            break
    if pair:
        a, b, (c1, c2) = pair
        joins.append(f"   // A multi-column join, over two columns the tables share.\n"
                     f"   Join dense_MultiCol({a}.{c1} = {b}.{c1} and {a}.{c2} = {b}.{c2})")

    # ---- non-equality, or, and mixed -----------------------------------------------------
    # TWO tables, always. A join whose condition names only one table is rejected with "The
    # system can only find one table in the join. Please use the '{target}' notation" -- the
    # engine reads it as an undirected self-join. That is a COMPILE error, so the file still
    # parses and the mistake survives any parse-only check.
    num = _tables_with(c, "float", 1) or _tables_with(c, "int", 1)
    if len(num) >= 2:
        ta, tb = num[0], num[1]
        fa = (_cols(c, ta, "float") or _cols(c, ta, "int"))[0]
        fb = (_cols(c, tb, "float") or _cols(c, tb, "int"))[0]
        joins.append(f"   // Non-equality join. `=` is the only operator the base model uses.\n"
                     f"   Join dense_GreaterThan({ta}.{fa} > {tb}.{fb})")
        joins.append(f"   // `or`, and a mixed condition PARENTHESISED because and/or are\n"
                     f"   // equal-precedence and right-associative.\n"
                     f"   Join dense_OrMixed(({ta}.{fa} > {tb}.{fb}) or "
                     f"({ta}.{fa} is null and {tb}.{fb} is not null))")

    # ---- dynafunction join ---------------------------------------------------------------
    strt = _tables_with(c, "string", 2)
    if len(strt) >= 2:
        ta, tb = strt[0], strt[1]
        a1, a2 = _cols(c, ta, "string")[:2]
        b1 = _cols(c, tb, "string")[0]
        joins.append(f"   // Dynafunction inside a join condition, on one side and on both.\n"
                     f"   // Note toUpper, NOT upper -- `upper` is not a dynafunction, and\n"
                     f"   // neither name is validated until SQL generation.\n"
                     f"   Join dense_DynaOneSide(concat({ta}.{a1}, {ta}.{a2}) = {tb}.{b1})")
        joins.append(f"   Join dense_DynaBothSides(toUpper({ta}.{a1}) = toUpper({tb}.{b1}))")

    # ---- self-join -----------------------------------------------------------------------
    if strt:
        t = strt[0]
        pk = c.tables[t].pk[0]
        other = next((s for s in _cols(c, t, "string") if s != pk), None)  # noqa: E501
        if other:
            joins.append(f"   // Self-join. {{target}} names the far side of the same table.\n"
                         f"   Join dense_Self({t}.{other} = {{target}}.{pk})")

    L += joins + [""]

    # ---- filters -------------------------------------------------------------------------
    # The view's root: the table its ~groupBy and columns read.
    root = num[0] if num and strt else None
    view_filter = "dense_NotNull"
    if strt:
        t = strt[0]
        s1 = _cols(c, t, "string")[0]
        L += [f"   Filter dense_NotNull({t}.{s1} is not null)"]
        # RULE (hand fix d0367624b, 2026-09-22): a view's ~filter must read the view's own
        # root. A filter over a table the view never reads compiles in the engine and fails at
        # SQL generation; this platform refuses it at build. So when dense_NotNull reads
        # another table, the view gets its own NotNull filter over its root's primary key.
        if root and root != t:
            view_filter = f"dense_{root.split('_')[0].title()}NotNull"
            L += [
                "   // A view's ~filter must read the view's own root (or a table its joins",
                "   // reach): the engine compiles a filter over an unrelated table and fails",
                "   // at SQL generation; this platform refuses it at build (views are lifted",
                f"   // eagerly, strict entry — 2026-09-22). dense_Rollup roots at {root}.",
                f"   Filter {view_filter}({root}.{c.tables[root].pk[0]} is not null)",
            ]
        L += [
            "   // A MultiGrainFilter is referenced from a mapping exactly like a Filter;",
            "   // the distinction is consumed by the planner for join elision.",
            f"   MultiGrainFilter dense_Grain({t}.{s1} is not null)",
            "",
        ]

    # ---- views: all three directives, in the VIEW's order --------------------------------
    if num and strt:
        t = num[0]
        f1 = (_cols(c, t, "float") or _cols(c, t, "int"))[0]
        pk = c.tables[t].pk[0]
        L += [
            "   // Directive order here is ~filter, ~groupBy, ~distinct. A class mapping",
            "   // orders the last two the other way round.",
            "   View dense_Rollup",
            "   (",
            f"      ~filter {view_filter}",
            "      ~groupBy",
            "      (",
            f"         {t}.{pk}",
            "      )",
            "      ~distinct",
            f"      key: {t}.{pk} PRIMARY KEY,",
            f"      total: sum({t}.{f1})",
            "   )",
            "",
        ]

    L += [")", ""]
    return "\n".join(L)


if __name__ == "__main__":
    c = model.load()
    text = build(c)
    print(f"dense store: {len(text.splitlines())} lines")
    for k in ("Schema", "TabularFunction", "MultiGrainFilter", "Filter ", "View ", "Join "):
        print(f"  {k:<18}{text.count(k)}")
