// Copyright 2026 Legend Contributors
// SPDX-License-Identifier: Apache-2.0

package catalogfacts;

import com.legend.json.Json;
import com.legend.parser.SpecParser;
import com.legend.protocol.ProtocolEmitter;
import com.legend.protocol.SourceInformation;
import com.legend.sql.dialect.CatalogModel;
import com.legend.sql.dialect.CatalogRules;
import com.legend.sql.dialect.CatalogType;
import com.legend.sql.dialect.DuckDb;
import com.legend.sql.dialect.Postgres;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * A table's model -- the Pure Database, from its database's own catalog (DuckDB's, Postgres's) -- as
 * legend-lite writes it, for DataCube to write the SAME in TypeScript, with no WebAssembly, on any planner
 * (the user, 2026-10-01: a file opened in the tab, with legend-engine planning and no module).
 * GENERATED by RUNNING legend-lite, never by reading its source:
 *
 * <ul>
 *   <li>{@code rules <out.ts>}: each database's catalog-type decisions ({@link CatalogRules}: DuckDB's,
 *       Postgres's) and THE DuckDB catalog question the tab asks ({@link DuckDb#CATALOG_COLUMNS_SQL}) as
 *       data -- the TypeScript writer runs {@link CatalogRules#typeOf}'s algorithm on it and adds no type
 *       rule of its own, and no type string is parsed on either side;</li>
 *   <li>{@code corpus <out.ts>}: for a fixed corpus of REAL DuckDB tables, read back by that question,
 *       and of Postgres tables as the warehouse's Postgres catalog question answered them on Postgres 17
 *       (every type, awkward names, with and without a schema, convertible or not, and the refusals),
 *       what {@link CatalogModel#database}
 *       answers -- the Database text, the accessor (and its protocol, as the compiler parses it),
 *       the conversions, the excluded columns, or the refusal's message. DataCube's writer is tested
 *       against it: any drift fails the build.</li>
 * </ul>
 *
 * <p>Built by {@code //datacube:catalog_rules} and {@code //datacube:catalog_corpus}; the committed
 * copies are diff-tested ({@code bazel run //datacube:update_generated}).
 */
public final class CatalogFacts {

    private CatalogFacts() {
    }

    public static void main(String[] args) throws IOException {
        if (args.length != 2 || !(args[0].equals("rules") || args[0].equals("corpus"))) {
            throw new IllegalArgumentException("usage: CatalogFacts rules|corpus <out.ts>");
        }
        String text = args[0].equals("rules") ? rules() : corpus();
        Files.writeString(Path.of(args[1]), text, StandardCharsets.UTF_8);
    }

    private static final String HEAD = "// GENERATED by datacube/tools/catalogfacts/CatalogFacts.java, which RUNS legend-lite\n"
            + "// (DuckDb.CATALOG_RULES / CATALOG_COLUMNS_SQL, Postgres.CATALOG_RULES, CatalogModel.database, and a\n"
            + "// real DuckDB's catalog for the corpus) -- DO NOT EDIT. Regenerate:\n"
            + "// bazel run //datacube:update_generated; its diff test fails the build if this copy drifts.\n";

    private static String rules() {
        StringBuilder out = new StringBuilder(HEAD);
        out.append("\n/** How a source reads a column (CatalogType.Read): as stored; converted to be read at all; read as stored\n"
                + " *  in place (the UTC session) and converted only in a copy; or left out, no Database type holding it. */\n"
                + "export type CatalogRead = " + String.join(" | ", java.util.Arrays.stream(CatalogType.Read.values())
                        .map(r -> str(r.name())).toList()) + ";\n\n");
        out.append("/** How a Database declares a column of a canonical type (null: left out), the SQL over `%s` that\n"
                + " *  converts it at the source (null: none), and why it is left out (null: it is not). */\n"
                + "export interface CatalogType {\n  readonly read: CatalogRead;\n  readonly declared: string | null;\n"
                + "  readonly conversion: string | null;\n  readonly reason: string | null;\n}\n\n");
        out.append("/** How a database's dialect reads its own catalog (CatalogRules): a column's own type name that is an\n"
                + " *  alias; its canonical type (upper-cased) when that is the exact decimal -- DECIMAL(p,s) from the catalog's\n"
                + " *  precision and scale, else `unsizedDecimal` (null: refused); the canonical type's decision; else refused. */\n"
                + "export interface CatalogRules {\n  readonly database: string;\n"
                + "  readonly types: Readonly<Record<string, CatalogType>>;\n  readonly aliases: Readonly<Record<string, CatalogType>>;\n"
                + "  readonly refused: Readonly<Record<string, string>>;\n  readonly decimal: string;\n"
                + "  readonly unsizedDecimal: CatalogType | null;\n}\n\n");
        // each distinct decision once, by name: most types of a database share a handful
        List<CatalogRules> all = List.of(DuckDb.CATALOG_RULES, Postgres.CATALOG_RULES);
        Map<CatalogType, String> names = new java.util.LinkedHashMap<>();
        for (CatalogRules rules : all) {
            List<CatalogType> each = new ArrayList<>(rules.types().values());
            each.addAll(rules.aliases().values());
            if (rules.unsizedDecimal() != null) {
                each.add(rules.unsizedDecimal());
            }
            for (CatalogType t : each) {
                names.computeIfAbsent(t, k -> {
                    String base = (k.read().name() + "_" + (k.declared() == null ? "NONE" : k.declared()))
                            .toUpperCase(java.util.Locale.ROOT).replaceAll("[^A-Z0-9]+", "_").replaceAll("_+$", "");
                    String name = base;
                    for (int i = 2; names.containsValue(name); i++) {
                        name = base + "_" + i;
                    }
                    return name;
                });
            }
        }
        out.append("/** The decisions, each once. */\n");
        for (Map.Entry<CatalogType, String> e : names.entrySet()) {
            out.append("const ").append(e.getValue()).append(": CatalogType = ").append(type(e.getKey())).append(";\n");
        }
        out.append("\n/** Each database's rules, by its database type as a Pure connection names it. */\n");
        out.append("export const CATALOG_RULES: Readonly<Record<string, CatalogRules>> = {\n");
        for (CatalogRules rules : all) {
            out.append("  ").append(str(rules.database())).append(": {\n    database: ").append(str(rules.database()))
                    .append(",\n    types: {\n");
            for (Map.Entry<String, CatalogType> e : rules.types().entrySet()) {
                out.append("      ").append(str(e.getKey())).append(": ").append(names.get(e.getValue())).append(",\n");
            }
            out.append("    },\n    aliases: {\n");
            for (Map.Entry<String, CatalogType> e : new java.util.TreeMap<>(rules.aliases()).entrySet()) {
                out.append("      ").append(str(e.getKey())).append(": ").append(names.get(e.getValue())).append(",\n");
            }
            out.append("    },\n    refused: {\n");
            for (Map.Entry<String, String> e : rules.refused().entrySet()) {
                out.append("      ").append(str(e.getKey())).append(": ").append(str(e.getValue())).append(",\n");
            }
            out.append("    },\n    decimal: ").append(str(rules.decimal())).append(",\n    unsizedDecimal: ")
                    .append(rules.unsizedDecimal() == null ? "null" : names.get(rules.unsizedDecimal())).append(",\n  },\n");
        }
        out.append("};\n\n/** THE question every reader asks DuckDB's catalog for a table's columns ({schema}, {table}: SQL string\n"
                + " *  literals). */\n");
        out.append("export const CATALOG_COLUMNS_SQL = ").append(str(DuckDb.CATALOG_COLUMNS_SQL)).append(";\n");
        return out.toString();
    }

    private static String type(CatalogType t) {
        return "{ read: " + str(t.read().name()) + ", declared: " + nullable(t.declared())
                + ", conversion: " + nullable(t.conversion()) + ", reason: " + nullable(t.reason()) + " }";
    }

    private static String nullable(String s) {
        return s == null ? "null" : str(s);
    }

    /**
     * One table to model: a real DuckDB table (its DDL), read back by THE catalog question -- or, for
     * what DuckDB will not create (two columns a case apart, none at all), the catalog rows as given.
     */
    private record Case(String name, String databaseType, String path, String schema, String table, String ddl,
            List<CatalogModel.Column> given, boolean convertible) {
    }

    private static Case real(String name, String path, String schema, String table, String ddl, boolean convertible) {
        return new Case(name, "DuckDB", path, schema, table, ddl, null, convertible);
    }

    /** A Postgres table, by the rows the warehouse's Postgres catalog question answered for it (Postgres 17.11). */
    private static Case postgres(String name, String schema, String table, List<CatalogModel.Column> rows, boolean convertible) {
        return new Case(name, "Postgres", "local::DB", schema, table, null, rows, convertible);
    }

    private static CatalogModel.Column pg(String name, String dataType, String logical) {
        return new CatalogModel.Column(name, dataType, logical, null, null, false);
    }

    /** A probe table of every kind of Postgres column, as Postgres 17.11's catalog answered (2026-10-02). */
    private static final List<CatalogModel.Column> PG_PROBE = List.of(
            new CatalogModel.Column("id", "integer", "int4", null, null, true), pg("i2", "smallint", "int2"),
            pg("i8", "bigint", "int8"), pg("n", "numeric", "numeric"),
            new CatalogModel.Column("n12", "numeric(12,3)", "numeric", 12, 3, false), pg("r", "real", "float4"),
            pg("d", "double precision", "float8"), pg("b", "boolean", "bool"), pg("t", "text", "text"),
            pg("vc", "character varying(20)", "varchar"), pg("ch", "character(3)", "bpchar"), pg("dt", "date", "date"),
            pg("ts", "timestamp without time zone", "timestamp"), pg("tstz", "timestamp with time zone", "timestamptz"),
            pg("tm", "time without time zone", "time"), pg("tmtz", "time with time zone", "timetz"),
            pg("iv", "interval", "interval"), pg("u", "uuid", "uuid"), pg("j", "json", "json"), pg("jb", "jsonb", "jsonb"),
            pg("ia", "integer[]", "ARRAY"), pg("ta", "text[]", "ARRAY"), pg("ip", "inet", "inet"), pg("cidr_", "cidr", "cidr"),
            pg("mac", "macaddr", "macaddr"), pg("m", "money", "money"), pg("x", "xml", "xml"), pg("by", "bytea", "bytea"),
            pg("pt", "point", "point"), pg("mo", "probe.mood", "ENUM"), pg("bits", "bit(3)", "bit"),
            pg("vb", "bit varying", "varbit"), pg("rng", "int4range", "int4range"), pg("ts_v", "tsvector", "tsvector"),
            pg("oid_", "oid", "oid"), new CatalogModel.Column("dom", "probe.pos", "numeric", 9, 2, false),
            pg("comp", "probe.pair", "COMPOSITE"), pg("mood_arr", "probe.mood[]", "ARRAY"),
            new CatalogModel.Column("nn", "integer", "int4", null, null, true));

    private static String corpus() throws IOException {
        List<Case> cases = new ArrayList<>();
        // a column of every type DuckDB will create, each through the catalog: the decided ones, the
        // shapes of the parameterised ones, the alias, a user's enum type, and the refused
        for (String type : List.of("VARCHAR", "VARCHAR(12)", "TEXT", "BOOLEAN", "TINYINT", "SMALLINT", "INTEGER", "BIGINT",
                "UTINYINT", "USMALLINT", "UINTEGER", "UBIGINT", "HUGEINT", "UHUGEINT", "FLOAT", "DOUBLE", "DECIMAL(18,3)",
                "DECIMAL(4,1)", "NUMERIC(10)", "DECIMAL(38,0)", "DATE", "TIMESTAMP", "TIMESTAMP_S", "TIMESTAMP_MS",
                "TIMESTAMP_NS", "TIMESTAMPTZ", "TIME", "TIMETZ", "TIME_NS", "UUID", "INTERVAL", "BIT", "BIGNUM", "VARINT",
                "JSON", "ENUM('a', 'b')", "mood", "STRUCT(a INTEGER, b VARCHAR)", "INTEGER[]", "INTEGER[3]",
                "STRUCT(a INTEGER)[]", "MAP(VARCHAR, INTEGER)", "UNION(a INTEGER, b VARCHAR)", "BLOB")) {
            // (no VARIANT: DuckDB 1.5 cannot store one in a table yet -- "Not implemented")
            cases.add(real("type " + type, "local::DB", null, "t", "c " + type, true));
        }
        String mixed = "region VARCHAR, \"trade date\" DATE, amount DECIMAL(18,2), big HUGEINT, \"at\" TIMESTAMPTZ, id UUID,"
                + " payload STRUCT(a INTEGER), \"say \"\"hi\"\"\" VARCHAR, \"back\\slash\" INTEGER, _ok9 BIGINT,"
                + " \"9lead\" DOUBLE, doc JSON";
        cases.add(real("mixed, no schema", "local::DB", null, "trades", mixed, true));
        cases.add(real("mixed, a schema", "local::DB", "main", "trades", mixed, true));
        cases.add(real("mixed, read-only", "local::DB", "sales", "v_orders", mixed, false));
        cases.add(real("awkward schema and table", "local::DB", "my s", "my t", mixed, true));
        cases.add(real("quoted table", "warehouse::DB", null, "Trades \"2024\"", mixed, true));
        cases.add(real("another package", "my::pkg::Db", "s", "t", "x INTEGER", true));
        cases.add(real("NOT NULL columns, a primary key", "local::DB", null, "t",
                "id INTEGER PRIMARY KEY, n DOUBLE NOT NULL, d DECIMAL(9,2) NOT NULL, u UUID NOT NULL, maybe DOUBLE", true));
        cases.add(real("a dot in the table", "local::DB", null, "a.b", "c INTEGER", true));
        cases.add(real("a brace in the schema", "local::DB", "s{", "t", "c INTEGER", true));
        cases.add(real("every column needs a conversion, read-only", "local::DB", null, "t", "u UUID, h HUGEINT", false));
        // a Postgres table as the warehouse lists it: a zoned timestamp read in place, bytes left out, by name
        cases.add(real("a zoned timestamp and bytes, read-only", "local::DB", "sales", "orders",
                "id BIGINT NOT NULL, ordered_at TIMESTAMPTZ NOT NULL, photo BLOB, ref UUID", false));
        cases.add(real("a zoned timestamp and bytes, convertible", "local::DB", null, "orders",
                "id BIGINT NOT NULL, ordered_at TIMESTAMPTZ NOT NULL, photo BLOB", true));
        cases.add(real("only bytes", "local::DB", null, "t", "b BLOB", true));
        cases.add(postgres("postgres: every kind of column, read-only", "probe", "kinds", PG_PROBE, false));
        cases.add(postgres("postgres: every kind of column, convertible", null, "kinds", PG_PROBE, true));
        cases.add(postgres("postgres: an extension type and a user range", "public", "t", List.of(
                pg("id", "integer", "int4"), pg("email", "citext", "USER-DEFINED"), pg("span", "floatrange", "RANGE")), false));
        cases.add(postgres("postgres: only bytes", "public", "t", List.of(pg("b", "bytea", "bytea")), false));
        cases.add(postgres("postgres: a type this dialect does not read", "public", "t", List.of(
                pg("id", "integer", "int4"), pg("q", "quaternion", "quaternion")), false));
        cases.add(new Case("no columns", "DuckDB", "local::DB", null, "t", null, List.of(), true));
        cases.add(new Case("two columns a case apart", "DuckDB", "local::DB", null, "t", null, List.of(
                new CatalogModel.Column("Amount", "INTEGER", "INTEGER", 32, 0, false),
                new CatalogModel.Column("amount", "DOUBLE", "DOUBLE", 53, 0, false)), true));

        StringBuilder out = new StringBuilder(HEAD);
        out.append("\n/** A catalog column, as THE catalog question answers it. */\n"
                + "export interface CorpusColumn {\n  readonly name: string;\n  readonly dataType: string;\n"
                + "  readonly logicalType: string | null;\n  readonly precision: number | null;\n  readonly scale: number | null;\n"
                + "  readonly notNull: boolean;\n}\n\n");
        out.append("/** What legend-lite's CatalogModel.database answers for each table of a fixed corpus: real DuckDB tables,\n"
                + " *  and Postgres tables as the warehouse's Postgres catalog question answered them. */\n");
        out.append("export const CATALOG_CORPUS: readonly {\n  readonly name: string;\n"
                + "  readonly input: { readonly databaseType: string; readonly path: string; readonly schema: string | null;\n"
                + "    readonly table: string;\n"
                + "    readonly columns: readonly CorpusColumn[]; readonly convertible: boolean };\n"
                + "  readonly expected:\n    | { readonly text: string; readonly accessor: string; readonly source: unknown;\n"
                + "        readonly conversions: readonly { readonly column: string; readonly sql: string }[];\n"
                + "        readonly excluded: readonly string[] }\n    | { readonly error: string };\n}[] = [\n");
        try (java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:duckdb:");
             java.sql.Statement st = conn.createStatement()) {
            st.execute("CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy')");
            for (Case c : cases) {
                List<CatalogModel.Column> columns = c.given() != null ? c.given() : read(st, c);
                StringBuilder cols = new StringBuilder("[");
                for (CatalogModel.Column col : columns) {
                    cols.append(cols.length() > 1 ? ", " : "").append("{ name: ").append(str(col.name()))
                            .append(", dataType: ").append(str(col.dataType()))
                            .append(", logicalType: ").append(col.logicalType() == null ? "null" : str(col.logicalType()))
                            .append(", precision: ").append(col.precision()).append(", scale: ").append(col.scale())
                            .append(", notNull: ").append(col.notNull()).append(" }");
                }
                cols.append("]");
                out.append("  {\n    name: ").append(str(c.name())).append(",\n    input: { databaseType: ")
                        .append(str(c.databaseType())).append(", path: ").append(str(c.path()))
                        .append(", schema: ").append(c.schema() == null ? "null" : str(c.schema()))
                        .append(", table: ").append(str(c.table())).append(", columns: ").append(cols)
                        .append(", convertible: ").append(c.convertible()).append(" },\n    expected: ");
                try {
                    CatalogModel.Database db = CatalogModel.database(c.path(), c.schema(), c.table(), columns,
                            com.legend.database.Databases.dialect(com.legend.database.Databases.named(c.databaseType())),
                            c.convertible());
                    // the accessor's protocol, as the in-tab module gives it: the compiler's parse of its own text
                    Json.Obj lambda = Json.parseObject(SourceInformation.strip(
                            ProtocolEmitter.emitLambda(SpecParser.parseLambda("|" + db.accessor()))));
                    String source = Json.toCompact(lambda.getArr("body").items().get(0));
                    StringBuilder conversions = new StringBuilder("[");
                    for (CatalogModel.Conversion v : db.conversions()) {
                        conversions.append(conversions.length() > 1 ? ", " : "").append("{ column: ").append(str(v.column()))
                                .append(", sql: ").append(str(v.sql())).append(" }");
                    }
                    conversions.append("]");
                    StringBuilder excluded = new StringBuilder("[");
                    for (String e : db.excluded()) {
                        excluded.append(excluded.length() > 1 ? ", " : "").append(str(e));
                    }
                    excluded.append("]");
                    out.append("{\n      text: ").append(str(db.text())).append(",\n      accessor: ").append(str(db.accessor()))
                            .append(",\n      source: ").append(source).append(",\n      conversions: ").append(conversions)
                            .append(",\n      excluded: ").append(excluded).append(",\n    },\n  },\n");
                } catch (RuntimeException e) {
                    out.append("{ error: ").append(str(e.getMessage())).append(" },\n  },\n");
                }
            }
        } catch (java.sql.SQLException e) {
            throw new IOException("the corpus's DuckDB: " + e.getMessage(), e);
        }
        out.append("];\n");
        return out.toString();
    }

    /** A case's real table, created in its own schema and read back by THE catalog question. */
    private static List<CatalogModel.Column> read(java.sql.Statement st, Case c) throws java.sql.SQLException {
        String schema = c.schema() == null ? "main" : c.schema();
        st.execute("CREATE SCHEMA IF NOT EXISTS " + sqlIdent(schema));
        st.execute("DROP TABLE IF EXISTS " + sqlIdent(schema) + "." + sqlIdent(c.table()));
        st.execute("CREATE TABLE " + sqlIdent(schema) + "." + sqlIdent(c.table()) + " (" + c.ddl() + ")");
        List<CatalogModel.Column> out = new ArrayList<>();
        String sql = DuckDb.CATALOG_COLUMNS_SQL.replace("{schema}", sqlString(schema)).replace("{table}", sqlString(c.table()));
        try (java.sql.ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) {
                out.add(new CatalogModel.Column(rs.getString(1), rs.getString(2), rs.getString(3),
                        (Integer) rs.getObject(4), (Integer) rs.getObject(5), rs.getBoolean(6)));
            }
        }
        if (out.isEmpty()) {
            throw new java.sql.SQLException("the catalog question read no column of " + schema + "." + c.table());
        }
        return out;
    }

    private static String sqlIdent(String name) {
        return "\"" + name.replace("\"", "\"\"") + "\"";
    }

    private static String sqlString(String text) {
        return "'" + text.replace("'", "''") + "'";
    }

    /** A TypeScript string literal. */
    private static String str(String s) {
        StringBuilder out = new StringBuilder("'");
        for (char ch : s.toCharArray()) {
            switch (ch) {
                case '\\' -> out.append("\\\\");
                case '\'' -> out.append("\\'");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> {
                    if (ch < 0x20) {
                        out.append(String.format(java.util.Locale.ROOT, "\\u%04x", (int) ch));
                    } else {
                        out.append(ch);
                    }
                }
            }
        }
        return out.append("'").toString();
    }
}
