// Copyright 2026 Legend Contributors
// SPDX-License-Identifier: Apache-2.0

package catalogfacts;

import com.legend.sql.dialect.CatalogRules;
import com.legend.sql.dialect.CatalogType;
import com.legend.sql.dialect.DuckDb;
import com.legend.sql.dialect.Postgres;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Each database's catalog-type decisions ({@link CatalogRules}: DuckDB's, Postgres's) and THE DuckDB catalog
 * question the tab asks ({@link DuckDb#CATALOG_COLUMNS_SQL}) as data, for DataCube to write a table's model the SAME
 * in TypeScript (catalog-facts.ts): the TypeScript writer runs {@link CatalogRules#typeOf}'s algorithm on it and adds
 * no type rule of its own, and no type string is parsed on either side. GENERATED by RUNNING legend-lite, never by
 * reading its source.
 *
 * <p>Built by {@code //datacube:catalog_rules} over {@code //core:sql_dialect} alone, so only a change to the
 * dialects reruns it; the committed copy is diff-tested ({@code bazel run //datacube:update_generated}).
 * {@link CatalogFacts} (the corpus) shares its TypeScript string writer.
 */
public final class CatalogRulesFacts {

    private CatalogRulesFacts() {
    }

    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            throw new IllegalArgumentException("usage: CatalogRulesFacts <out.ts>");
        }
        Files.writeString(Path.of(args[0]), rules(), StandardCharsets.UTF_8);
    }

    private static final String HEAD = "// GENERATED by datacube/tools/catalogfacts/CatalogRulesFacts.java, which RUNS legend-lite\n"
            + "// (DuckDb.CATALOG_RULES / CATALOG_COLUMNS_SQL, Postgres.CATALOG_RULES) -- DO NOT EDIT. Regenerate:\n"
            + "// bazel run //datacube:update_generated; its diff test fails the build if this copy drifts.\n";

    static String rules() {
        StringBuilder out = new StringBuilder(HEAD);
        out.append("\n/** How a source reads a column (CatalogType.Read): as stored; converted to be read at all; read as stored\n"
                + " *  in place (the UTC session) and converted only in a copy; or left out, no Database type holding it. */\n"
                + "export type CatalogRead = " + String.join(" | ", java.util.Arrays.stream(CatalogType.Read.values())
                        .map(r -> str(r.name())).toList()) + ";\n\n");
        out.append("/** How a Database declares a column of a canonical type (null: left out), the SQL over `%s` that\n"
                + " *  converts it at the source (null: none), and why it is left out (null: it is not). */\n"
                + "export interface CatalogType {\n  readonly read: CatalogRead;\n  readonly declared: string | null;\n"
                + "  readonly conversion: string | null;\n  readonly reason: string | null;\n}\n\n");
        out.append("/** How a database's dialect reads its own catalog (CatalogRules): a column's own type name that is an\n"
                + " *  alias; its canonical type (upper-cased) when that is the exact decimal -- DECIMAL(p,s) from the catalog's\n"
                + " *  precision and scale, else `unsizedDecimal` (null: refused); the canonical type's decision; else refused. */\n"
                + "export interface CatalogRules {\n  readonly database: string;\n"
                + "  readonly types: Readonly<Record<string, CatalogType>>;\n  readonly aliases: Readonly<Record<string, CatalogType>>;\n"
                + "  readonly refused: Readonly<Record<string, string>>;\n  readonly decimal: string;\n"
                + "  readonly unsizedDecimal: CatalogType | null;\n}\n\n");
        // each distinct decision once, by name: most types of a database share a handful
        List<CatalogRules> all = List.of(DuckDb.CATALOG_RULES, Postgres.CATALOG_RULES);
        Map<CatalogType, String> names = new java.util.LinkedHashMap<>();
        for (CatalogRules rules : all) {
            List<CatalogType> each = new ArrayList<>(rules.types().values());
            each.addAll(rules.aliases().values());
            if (rules.unsizedDecimal() != null) {
                each.add(rules.unsizedDecimal());
            }
            for (CatalogType t : each) {
                names.computeIfAbsent(t, k -> {
                    String base = (k.read().name() + "_" + (k.declared() == null ? "NONE" : k.declared()))
                            .toUpperCase(java.util.Locale.ROOT).replaceAll("[^A-Z0-9]+", "_").replaceAll("_+$", "");
                    String name = base;
                    for (int i = 2; names.containsValue(name); i++) {
                        name = base + "_" + i;
                    }
                    return name;
                });
            }
        }
        out.append("/** The decisions, each once. */\n");
        for (Map.Entry<CatalogType, String> e : names.entrySet()) {
            out.append("const ").append(e.getValue()).append(": CatalogType = ").append(type(e.getKey())).append(";\n");
        }
        out.append("\n/** Each database's rules, by its database type as a Pure connection names it. */\n");
        out.append("export const CATALOG_RULES: Readonly<Record<string, CatalogRules>> = {\n");
        for (CatalogRules rules : all) {
            out.append("  ").append(str(rules.database())).append(": {\n    database: ").append(str(rules.database()))
                    .append(",\n    types: {\n");
            for (Map.Entry<String, CatalogType> e : rules.types().entrySet()) {
                out.append("      ").append(str(e.getKey())).append(": ").append(names.get(e.getValue())).append(",\n");
            }
            out.append("    },\n    aliases: {\n");
            for (Map.Entry<String, CatalogType> e : new java.util.TreeMap<>(rules.aliases()).entrySet()) {
                out.append("      ").append(str(e.getKey())).append(": ").append(names.get(e.getValue())).append(",\n");
            }
            out.append("    },\n    refused: {\n");
            for (Map.Entry<String, String> e : rules.refused().entrySet()) {
                out.append("      ").append(str(e.getKey())).append(": ").append(str(e.getValue())).append(",\n");
            }
            out.append("    },\n    decimal: ").append(str(rules.decimal())).append(",\n    unsizedDecimal: ")
                    .append(rules.unsizedDecimal() == null ? "null" : names.get(rules.unsizedDecimal())).append(",\n  },\n");
        }
        out.append("};\n\n/** THE question every reader asks DuckDB's catalog for a table's columns ({schema}, {table}: SQL string\n"
                + " *  literals). */\n");
        out.append("export const CATALOG_COLUMNS_SQL = ").append(str(DuckDb.CATALOG_COLUMNS_SQL)).append(";\n");
        return out.toString();
    }

    private static String type(CatalogType t) {
        return "{ read: " + str(t.read().name()) + ", declared: " + nullable(t.declared())
                + ", conversion: " + nullable(t.conversion()) + ", reason: " + nullable(t.reason()) + " }";
    }

    private static String nullable(String s) {
        return s == null ? "null" : str(s);
    }

    /** A TypeScript string literal (single-quoted, escaped). */
    static String str(String s) {
        StringBuilder out = new StringBuilder("'");
        for (char ch : s.toCharArray()) {
            switch (ch) {
                case '\\' -> out.append("\\\\");
                case '\'' -> out.append("\\'");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> {
                    if (ch < 0x20) {
                        out.append(String.format(java.util.Locale.ROOT, "\\u%04x", (int) ch));
                    } else {
                        out.append(ch);
                    }
                }
            }
        }
        return out.append("'").toString();
    }
}
