// Copyright 2026 Legend Contributors
// SPDX-License-Identifier: Apache-2.0

package typefacts;

import com.legend.compiler.element.type.PlatformTypes;
import com.legend.compiler.element.type.Type;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;

/**
 * legend-lite's facts DataCube mirrors -- its type families and the pivot separator --
 * GENERATED by running legend-lite's own type lattice and constants
 * (docs/DATACUBE_TYPES_TO_SERVER_2026_09_27.md, decision D1): every type name either
 * compiler reports for a column -- legend-lite's plain primitives by leaf and by path,
 * legend-engine's precise primitives by path (each aliased to the parent legend-pure
 * declares) and Variant -- to its plain primitive and its family. Nothing is read out of
 * source text; the table is what {@link Type.Primitive} says.
 *
 * <p>Usage: {@code TypeFacts <out.ts>}. Built by {@code //datacube:type_facts}; the
 * committed copy is diff-tested ({@code bazel run //datacube:update_generated}).
 */
public final class TypeFacts {

    private TypeFacts() {
    }

    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            throw new IllegalArgumentException("usage: TypeFacts <out.ts>");
        }
        Map<String, String[]> facts = new TreeMap<>();
        for (Type.Primitive p : Type.Primitive.values()) {
            put(facts, p.typeName(), p);
            put(facts, p.qualifiedName(), p);
        }
        for (Map.Entry<String, Type.Primitive> e : Type.Primitive.byFqn().entrySet()) {
            put(facts, e.getKey(), e.getValue());
        }
        String variant = PlatformTypes.VARIANT.substring(PlatformTypes.VARIANT.lastIndexOf("::") + 2);
        facts.put(variant, new String[] {variant, "variant"});
        facts.put(PlatformTypes.VARIANT, new String[] {variant, "variant"});
        // Pure's top type: a column holding values of different types (a tree's label
        // column, an Ad Hoc column of several measures) is typed Any, as upstream types it
        String any = PlatformTypes.ANY.substring(PlatformTypes.ANY.lastIndexOf("::") + 2);
        facts.put(any, new String[] {any, "any"});
        facts.put(PlatformTypes.ANY, new String[] {any, "any"});

        StringBuilder out = new StringBuilder();
        out.append("// GENERATED by engine-client/tools/typefacts/TypeFacts.java, which RUNS legend-lite (its type\n")
                .append("// lattice, Type.Primitive, and its constants) -- DO NOT EDIT. Regenerate: bazel run //engine-client:update_generated;\n")
                .append("// its diff test fails the build if this copy drifts from legend-lite.\n")
                .append("// docs/DATACUBE_TYPES_TO_SERVER_2026_09_27.md, decision D1.\n\n")
                .append("/** A type's family, as legend-lite's lattice groups it (Type.Primitive.Family), Variant, and Pure's top type Any. */\n")
                .append("export type TypeFamily = 'numeric' | 'text' | 'boolean' | 'temporal' | 'binary' | 'variant' | 'any';\n\n")
                .append("/** A reported type name's plain primitive and its family. */\n")
                .append("export interface TypeFact {\n")
                .append("  readonly plain: string;\n")
                .append("  readonly family: TypeFamily;\n")
                .append("}\n\n")
                .append("/**\n")
                .append(" * Every type name a compiler reports for a column: legend-lite's plain primitives\n")
                .append(" * (by leaf and by path), legend-engine's precise primitives (by path, each to the\n")
                .append(" * parent legend-pure declares), Variant and Any.\n")
                .append(" */\n")
                .append("export const TYPE_FACTS: Readonly<Record<string, TypeFact>> = {\n");
        for (Map.Entry<String, String[]> e : facts.entrySet()) {
            out.append("  '").append(e.getKey()).append("': { plain: '").append(e.getValue()[0])
                    .append("', family: '").append(e.getValue()[1]).append("' },\n");
        }
        out.append("};\n\n")
                .append("/** How a pivot's generated column name joins its parts (Type.RelationType.PIVOT_SEPARATOR). */\n")
                .append("export const PIVOT_SEPARATOR = '")
                .append(Type.RelationType.PIVOT_SEPARATOR.replace("\\", "\\\\").replace("'", "\\'"))
                .append("';\n");
        Files.writeString(Path.of(args[0]), out.toString(), StandardCharsets.UTF_8);
    }

    private static void put(Map<String, String[]> facts, String name, Type.Primitive p) {
        facts.put(name, new String[] {p.typeName(), p.family().name().toLowerCase(Locale.ROOT)});
    }
}
