// GENERATED by //spec:gen_imports from legend-engine's CompileContext.META_IMPORTS -- do not edit.
// Regenerate: bazel run //:update_generated
package com.legend.compiler;

import java.util.List;

/**
 * The implicit import group every element resolves through, walked FIRST-MATCH: the engine's
 * sequence ({@code CompileContext.META_IMPORTS}: legend-pure's {@code system::imports::coreImport}
 * plus the packages the engine adds, at the engine's positions). The order is semantic;
 * {@code CoreImportsParityTest} holds it.
 */
public final class CoreImports {

    private CoreImports() {}

    /** The packages, in the engine's order. */
    public static final List<String> SEQUENCE = List.of(
            "meta::pure::metamodel",
            "meta::pure::metamodel::type",
            "meta::pure::metamodel::type::generics",
            "meta::pure::metamodel::relationship",
            "meta::pure::metamodel::valuespecification",
            "meta::pure::metamodel::multiplicity",
            "meta::pure::metamodel::function",
            "meta::pure::metamodel::function::property",
            "meta::pure::metamodel::extension",
            "meta::pure::metamodel::import",
            "meta::pure::metamodel::variant",
            "meta::pure::functions::date",
            "meta::pure::functions::string",
            "meta::pure::functions::collection",
            "meta::pure::functions::meta",
            "meta::pure::functions::constraints",
            "meta::pure::functions::lang",
            "meta::pure::functions::boolean",
            "meta::pure::functions::tools",
            "meta::pure::functions::io",
            "meta::pure::functions::math",
            "meta::pure::functions::asserts",
            "meta::pure::functions::test",
            "meta::pure::functions::multiplicity",
            "meta::pure::functions::relation",
            "meta::pure::metamodel::relation",
            "meta::pure::router",
            "meta::pure::service",
            "meta::pure::tds",
            "meta::pure::tools",
            "meta::pure::profiles",
            "meta::pure::precisePrimitives");
}
