// Guardrails on the shape of the source, in the spirit of the repo's
// own CodeShapeGuardrailTest: each one exists because the mistake it
// bans actually happened here.

import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { Sources } from '../../tools/js/runfiles.mts';

// the sources this reads, as the BUILD target declares them (Bazel workplan P3-29): it walks no directory
const SOURCES = new Sources('SOURCES', 'datacube');
const sources = (dir: string): string[] => SOURCES.under(dir, '.ts');

// the engine client was datacube/src until 2026-10-04: its files keep DataCube's guardrails
const FILES = [...sources('src'), ...sources('../engine-client/src')];

function isComment(line: string): boolean {
  const t = line.trim();
  return t.startsWith('//') || t.startsWith('*') || t.startsWith('/*');
}

describe('source guardrails', () => {
  it('finds source files at all', () => {
    // A guardrail that scans nothing passes for the wrong reason.
    assert.ok(FILES.length > 10, `${FILES.length} files`);
  });

  it('has no cross-realm DOM instanceof checks', () => {
    // This bit twice. The constructor belongs to the document's
    // realm, so in an iframe -- or a test DOM -- the check is false
    // and the code silently does nothing. Duck-type the method
    // actually used instead.
    const bad: string[] = [];
    for (const file of FILES) {
      SOURCES.read(file)
        .split('\n')
        .forEach((line, i) => {
          if (isComment(line)) return;
          if (
            /instanceof\s+(HTMLElement|Element|Node|HTMLInputElement)\b/.test(
              line,
            )
          ) {
            bad.push(`${file}:${i + 1}`);
          }
        });
    }
    assert.deepEqual(bad, [], `duck-type instead: ${bad.join(', ')}`);
  });

  it('has no literal control characters in source', () => {
    // Two separators were written as literal NUL bytes by accident.
    // An invisible byte survives no reformat and no code review, and
    // it silently breaks every search for the code around it.
    const control = new RegExp('[\\u0000-\\u0008\\u000b\\u000c\\u000e-\\u001f]');
    const bad: string[] = [];
    for (const file of FILES) {
      if (control.test(SOURCES.read(file))) bad.push(file);
    }
    assert.deepEqual(bad, [], `use an escape sequence: ${bad.join(', ')}`);
  });

  it('writes its own words in one locale (Bazel workplan P3-29)', () => {
    // A row count or a clock time the app writes into a message read differently on every
    // machine: toLocaleString() takes the browser's locale. The app's words name UI_LOCALE
    // (engine-client/src/locale.ts); a column's display format names its own.
    const bare = /\.toLocale(String|DateString|TimeString)\((\)|\s*undefined\b)/;
    const hits: string[] = [];
    for (const file of [...FILES, ...sources('demo')]) {
      SOURCES.read(file).split('\n').forEach((line, i) => {
        if (!isComment(line) && bare.test(line)) hits.push(`${file}:${i + 1}: ${line.trim()}`);
      });
    }
    assert.deepEqual(hits, [], `name the locale (UI_LOCALE):\n${hits.join('\n')}`);
  });

  it('keeps the demo-only planner out of the product', () => {
    // "One planner" is an architectural commitment, and a convenient
    // second one is exactly how such commitments rot.
    const bad = FILES.filter((f) =>
      /DemoOnlyPlanner|filterToSql/.test(SOURCES.read(f)),
    );
    assert.deepEqual(bad, [], `demo code in src: ${bad.join(', ')}`);
  });
});

describe('types come from the compiler (docs/DATACUBE_TYPES_TO_SERVER_2026_09_27.md)', () => {
  // A type's family (numeric, temporal, ...) is legend-lite's lattice, generated by
  // running it (engine-client/src/generated/lite-facts.ts) and read through engine-client/src/types.ts. Deciding by
  // comparing a type NAME is how seven drifting tables grew here: the menu knew no
  // Timestamp, the filter editor named types nothing produced, the numeric test left
  // out Decimal. None may come back.
  const NAMES = 'String|Integer|Float|Decimal|Number|Boolean|StrictDate|DateTime|Date|Variant|StrictTime|Timestamp|LatestDate';
  const COMPARED = new RegExp(`(===|!==)\\s*'(${NAMES})'|'(${NAMES})'\\s*(===|!==)|case '(${NAMES})':`);

  it('decides nothing by comparing a type name, outside the one reader', () => {
    const shipped = [...sources('src'), ...sources('../engine-client/src'), ...sources('demo')]
      .filter((f) => !f.includes('generated') && f !== '../engine-client/src/types.ts');
    const hits: string[] = [];
    for (const f of shipped) {
      SOURCES.read(f).split('\n').forEach((line, i) => {
        if (!isComment(line) && COMPARED.test(line)) hits.push(`${f}:${i + 1}: ${line.trim()}`);
      });
    }
    assert.deepEqual(hits, [], `decide by the compiler type's family (engine-client/src/types.ts):\n${hits.join('\n')}`);
  });
});

describe('queries are protocol, never Pure text (docs/DATACUBE_TYPES_TO_SERVER_2026_09_27.md, T4b)', () => {
  // Every query is a tree built with pure-protocol's Relation API (src/query.ts); Pure
  // text exists only where a PERSON reads or writes it, and the compiler owns both edges
  // (it parses what was typed and prints for display). A string holding Pure syntax is
  // how a TypeScript copy of the grammar's rules grows back -- the operator precedence
  // and the literal spelling that drifted once already.
  const PURE_SYNTAX = /(['"`])(?:(?!\1).)*(->|~\[|#>\{)/;
  /**
   * The text a person edits, and what it may say: the calculated-column editor's typing
   * help (its examples and completions are inserted into what the person types), one
   * refusal that suggests an expression to type, and one that names the accessor a table's
   * name cannot be read through.
   */
  const FOR_A_PERSON = new Map([
    ['src/calc.ts', 'the column editor\'s examples and completions'],
    ['src/query.ts', 'a refusal suggesting what to type'],
  ]);

  it('builds no Pure text outside what a person types', () => {
    const hits: string[] = [];
    for (const f of FILES.filter((x) => !x.includes('generated'))) {
      SOURCES.read(f).split('\n').forEach((line, i) => {
        if (isComment(line) || !PURE_SYNTAX.test(line)) return;
        const allowed = FOR_A_PERSON.get(f);
        if (allowed === undefined) hits.push(`${f}:${i + 1}: ${line.trim()}`);
      });
    }
    assert.deepEqual(hits, [], `build the query as a tree (src/query.ts):\n${hits.join('\n')}`);
  });

  it('keeps the exceptions to what they are for', () => {
    const count = (f: string): number => SOURCES.read(f).split('\n')
      .filter((line) => !isComment(line) && PURE_SYNTAX.test(line)).length;
    // pinned, so a query built as text cannot hide in an allowed file
    assert.equal(count('src/query.ts'), 1, 'query.ts: only the unpivotable refusal');
    assert.ok(count('src/calc.ts') > 0, 'calc.ts: the editor help still exists');
  });

  it('calls no TDS function: the Relation API only (the user, 2026-09-27)', () => {
    const TDS = /\bfn\(\s*'(project|restrict|olapGroupBy|renameColumns|groupByWithWindowSubset|tdsRows|extendWithWindow)'/;
    const hits: string[] = [];
    for (const f of FILES) {
      SOURCES.read(f).split('\n').forEach((line, i) => {
        if (!isComment(line) && TDS.test(line)) hits.push(`${f}:${i + 1}: ${line.trim()}`);
      });
    }
    assert.deepEqual(hits, [], hits.join('\n'));
  });
});

describe('keys and values are typed, never text sentinels or local Dates (T4c)', () => {
  // A group key is the cell's exact text or a real null (src/tree.ts GroupKey), and a value's
  // literal is written by its column's compiler type (src/query.ts literalNode). A text
  // sentinel for null collided with nothing only by luck; a JavaScript Date carried the
  // browser's time zone into a filter that has none.
  const QUERY_PATH = FILES.filter((f) => f === 'src/query.ts' || f === 'src/tree.ts'
    || f === 'src/treeview.ts' || f === 'src/plan.ts' || f.includes('src/adhoc'));

  it('reads the query path at all', () => {
    assert.ok(QUERY_PATH.length >= 6, QUERY_PATH.join(', '));
  });

  it('has no null-key sentinel and no Date on the query path', () => {
    const hits: string[] = [];
    for (const f of QUERY_PATH) {
      SOURCES.read(f).split('\n').forEach((line, i) => {
        if (!isComment(line) && /\\u0000null|instanceof Date|new Date\(/.test(line)) {
          hits.push(`${f}:${i + 1}: ${line.trim()}`);
        }
      });
    }
    assert.deepEqual(hits, [], hits.join('\n'));
  });
});

describe('there is exactly one planner, and no way to fall back to another', () => {
  // A shim planner cost three real bugs: snap building SQL by hand,
  // the snapped plane never redirecting, and the SQL panel showing
  // Pure. Every one was invisible because the demo silently ran on a
  // fake whose source was a bare SQL identifier, so the broken paths
  // happened to work.
  //
  // The rule is NOT "no fake may exist" -- a test injecting a stub is
  // fine, because that choice is static and never ships. The rule WAS
  // that shipped code must not be able to CHOOSE a planner at runtime.
  // REVISED (the user, 2026-09-30): the in-tab planner, legend-lite and
  // legend-engine are three addresses of the same service, so the demo
  // is ONE page and the planner a setting of it. What the old rule
  // protected stays: the choice is EXPLICIT (one place, the page's
  // `?planner=`, read once), always SHOWN (the status bar), and never
  // SUBSTITUTED (an unknown word is refused; an absent planner is said
  // and the page stops -- no fallback, the shape that hid the bugs).
  const shipped = [...sources('src'), ...sources('../engine-client/src'), ...sources('demo')];

  it('scans both shipped trees', () => {
    assert.ok(shipped.length > 10, `${shipped.length} files`);
  });

  // The two shipped implementations, and why two is not a betrayal of
  // "one planner".
  //
  // The rule bans a second IMPLEMENTATION -- a thing that must AGREE
  // with legend-lite about null ordering, coercion and aggregates,
  // and will therefore eventually disagree. It does not ban a second
  // TRANSPORT to the same implementation. `UpstreamPlanner` POSTs
  // to legend-lite's pure/v1 generatePlan, whose handler calls Compiler.plan;
  // `WasmPlanner` calls that same Compiler.plan compiled to
  // WebAssembly. There is one planner and two ways to reach it.
  //
  // That argument is only worth anything if something checks it, so
  // the next test requires the differentials that do.
  const PLANNERS = ['src/planner.ts', 'src/wasm-planner.ts'];

  it('implements Planner in exactly the two blessed shipped files', () => {
    const impls = shipped.filter((f) =>
      /implements\s+Planner\b/.test(SOURCES.read(f)),
    );
    assert.deepEqual(
      impls.sort(),
      [...PLANNERS].sort(),
      `a second planner is a second thing that must agree with the ` +
        `first about null ordering, coercion and aggregates. A new ` +
        `transport to legend-lite's own Compiler.plan may join this ` +
        `list; a planner that COMPUTES SQL itself may not: ${impls.join(', ')}`,
    );
  });

  it('keeps a differential behind the second transport', () => {
    // The allowance above rests entirely on the two transports being
    // checked against each other. If these harnesses go, the
    // allowance is unearned and the second file has to go with them.
    // Both are Bazel tests in the gate chain (//datacube:
    // wasm_differential_test, //wasm:differential_test), so they RUN
    // on every push; this only stops them being deleted.
    for (const f of ['test/wasm-differential/compare.ts',
      '../wasm/differential.mjs']) {
      assert.ok(SOURCES.has(f), `the wasm planner's differential is gone (${f})`
        + ' — either restore it or drop src/wasm-planner.ts');
    }
  });

  it('chooses a planner in ONE place, and nowhere constructs one from the address directly', () => {
    // The page's `?planner=` is read in `chosenPlane` (demo/boot.ts) and nowhere else; a planner
    // is BUILT from what it answers (demo/main.ts). A URL or env lookup in the same function as a
    // planner's construction would be a second, unreviewed place to choose.
    const readers = shipped.filter((f) => /searchParams\.get\('planner'\)|get\('planner'\)/.test(SOURCES.read(f)));
    assert.deepEqual(readers.map((f) => f.replace(/\\/g, '/')), ['demo/boot.ts'], `?planner= read in: ${readers.join(', ')}`);
    // index.html reads it too, ONLY to start the in-tab planner's download early: one read, in
    // the one script that adds the preload hint, and nothing else in the page reads it
    const page = SOURCES.read('demo/index.html');
    const reads = page.match(/get\('planner'\)/g) ?? [];
    assert.equal(reads.length, 1, 'index.html reads ?planner= once');
    const script = page.slice(page.lastIndexOf('<script>', page.indexOf("get('planner')")), page.indexOf('</script>', page.indexOf("get('planner')")));
    assert.match(script, /rel: 'preload'/, 'and only to add the preload hint');
    assert.doesNotMatch(script, /Planner|import|bundle/, 'never to build or load a planner');
    const boot = SOURCES.read('demo/boot.ts');
    assert.match(boot, /export function chosenPlane\(\)/);
    assert.match(boot, /throw new Error\(`\?planner=\$\{word\} is not a planner/, 'an unknown planner is refused, never guessed');
    const bad: string[] = [];
    for (const file of shipped) {
      const text = SOURCES.read(file);
      if (!/\bnew\s+\w*Planner\b/.test(text)) continue;
      const code = text.split('\n').filter((l) => !isComment(l)).join('\n');
      if (/URLSearchParams|process\.env|location\.search/.test(code)
          && /\bnew\s+\w*Planner\b/.test(code)) {
        // Only flag when the two are in the same FUNCTION-ish span;
        // main.ts legitimately reads ?remote= for the data source.
        const spans = code.split(/\n(?=(?:export )?(?:async )?function )/);
        for (const span of spans) {
          if (/\bnew\s+\w*Planner\b/.test(span)
              && /URLSearchParams|process\.env|location\.search/.test(span)) {
            bad.push(file);
            break;
          }
        }
      }
    }
    assert.deepEqual(bad, [], `runtime planner choice in: ${bad.join(', ')}`);
  });

  it('never recovers from an unreachable planner by substituting one', () => {
    // The specific shape that was here: a health probe, a catch, and
    // a fake returned from it.
    const bad: string[] = [];
    for (const file of shipped) {
      const text = SOURCES.read(file);
      // A `catch` block that constructs or returns a planner.
      if (/catch\s*(\([^)]*\))?\s*\{[^}]*\bnew\s+\w*Planner\b/s.test(text)) {
        bad.push(file);
      }
    }
    assert.deepEqual(bad, [], `fallback planner in: ${bad.join(', ')}`);
  });

  it('never chooses a RUNNER at runtime either', () => {
    // The same ban as the planner one, for the noun the engine plane
    // added. A runner decides WHO RUNS the query -- this tab, or an
    // engine that cannot be reached from it -- and a page that picks
    // by flag or URL is a page whose SQL pane and status bar can be
    // telling you about a back end you are not using.
    const bad: string[] = [];
    for (const file of shipped) {
      const text = SOURCES.read(file);
      if (!/\bnew\s+(?:RemoteRun|PlanThenRun)\b/.test(text)) continue;
      const code = text.split('\n').filter((l) => !isComment(l)).join('\n');
      const spans = code.split(/\n(?=(?:export )?(?:async )?function )/);
      for (const span of spans) {
        if (/\bnew\s+(?:RemoteRun|PlanThenRun)\b/.test(span)
            && /URLSearchParams|process\.env|location\.search/.test(span)) {
          bad.push(file);
          break;
        }
      }
    }
    assert.deepEqual(bad, [], `runtime runner choice in: ${bad.join(', ')}`);
  });

  it('never recovers from an unreachable engine by running locally', () => {
    // The fallback shape, for runners: a health probe, a catch, and a
    // runner built inside it. The engine plane has no local store at
    // all, so a fallback there would not be a degraded cube -- it
    // would be a cube showing different data under the same title.
    const bad: string[] = [];
    for (const file of shipped) {
      const text = SOURCES.read(file);
      if (/catch\s*(\([^)]*\))?\s*\{[^}]*\bnew\s+(?:RemoteRun|PlanThenRun)\b/s
        .test(text)) {
        bad.push(file);
      }
    }
    assert.deepEqual(bad, [], `fallback runner in: ${bad.join(', ')}`);
  });

  it('the refusal STOPS the page: it throws, it never returns a planner', () => {
    // Not "warns and carries on": a refusal that falls through builds the cube anyway, a grid of
    // invented numbers under a title that claims data.
    const boot = SOURCES.read('demo/boot.ts');
    const fn = boot.slice(boot.indexOf('export function refusePlanner('));
    assert.match(fn.slice(0, fn.indexOf('\n}\n')), /throw new Error\(/, 'refusePlanner must throw');
    assert.match(boot, /export function refusePlanner\([^)]*\): never/);
  });

  it('a server planner is asked first, and refused BEFORE it is built', () => {
    const demo = SOURCES.read('demo/planners.ts');
    const refuse = demo.indexOf('if (!answered) refusePlanner(');
    const build = demo.indexOf('new UpstreamPlanner');
    assert.ok(refuse > 0 && build > refuse, 'planners.ts must refuse an absent server planner before building it');
  });


  it('the default entry REFUSES to run without its planner module', () => {
    // Same rule, different absence. main.ts plans in the tab, so
    // there is no server to be down -- but the 4 MB module can be
    // missing, and the failure has to land BEFORE the grid exists.
    // `warmUp()` is what forces that: it loads and instantiates, so
    // an unavailable module rejects startup instead of surfacing as
    // a half-rendered grid on the user's first interaction.
    const demo = SOURCES.read('demo/planners.ts');
    assert.ok(
      /await\s+planner\.warmUp\(\)/.test(demo),
      'planners.ts must await warmUp() before handing the planner to boot,'
        + ' so a missing module fails startup rather than the first query',
    );
    const warm = demo.indexOf('warmUp()');
    const handed = demo.search(/return\s*\{\s*planner/);
    assert.ok(
      warm >= 0 && handed > warm,
      'warmUp() must come BEFORE the planner is handed to boot',
    );
  });

  it('runs the in-browser planner OFF the main thread', () => {
    // Measured, not theoretical. Building the boot layer is ~600ms of
    // synchronous WebAssembly with no yield point. On the main thread
    // it froze the page AND starved DuckDB: its startup slipped from
    // 409ms to 1038ms, and time-to-first-row got WORSE (1009 -> 1175)
    // when the planner was started earlier to "overlap" it. On a
    // worker the two genuinely run at once: 828ms.
    const demo = SOURCES.read('demo/planners.ts');
    assert.ok(
      /workerUrl\s*:/.test(demo),
      'demo/planners.ts must give WasmPlanner a workerUrl — without it the'
        + ' boot layer blocks the main thread and startup gets slower,'
        + ' not faster',
    );
  });

  it('keeps the shim gone from every entry point', () => {
    for (const f of ['main.ts', 'planners.ts', 'boot.ts']) {
      assert.equal(
        /DemoOnlyPlanner/.test(SOURCES.read(`demo/${f}`)),
        false,
        `the shim must be gone, not merely unreferenced (${f})`,
      );
    }
  });
});

describe('nothing is built and left unreachable', () => {
  // The audit that prompted the editor found most of this codebase
  // built, tested and unreachable: the context menu, the heatmap,
  // the rich exporters, drill-through, selection statistics, saved
  // views and named dimensions each had exactly ONE user -- the file
  // that defined it. They were libraries, not features, and no test
  // noticed, because every one of them had good unit tests.
  //
  // So: a module that exists to be used by the product must be
  // imported by the product, and called. app.ts is the product.
  const APP = SOURCES.read('src/app.ts');

  const REACHABLE: readonly [string, string][] = [
    ['the context menu', './ui/menu.ts'],
    ['the menu renderer', './ui/menu-view.ts'],
    ['the heatmap', './style.ts'],
    ['the rich exporters', './export-rich.ts'],
    ['plain export', './export.ts'],
    ['drill-through', './query.ts'],
    ['selection statistics', './selection.ts'],
    ['the saved cube', './cube-document.ts'],
    ['named dimensions', './dimensions.ts'],
    ['the editor', './ui/editor.ts'],
    ['the filter editor', './ui/filter-editor.ts'],
    ['the drag zones', './ui/pivot-panel.ts'],
    ['the columns tool panel', './ui/columns-panel.ts'],
    ['the configuration', './config.ts'],
  ];

  for (const [what, module] of REACHABLE) {
    it(`reaches ${what}`, () => {
      assert.ok(
        APP.includes(`from '${module}'`),
        `src/app.ts does not import ${module}; ${what} is unreachable`,
      );
    });
  }

  it('actually calls what it imports', () => {
    // Importing a module and never calling it would satisfy the
    // check above while leaving the feature just as unreachable.
    for (const call of [
      'buildMenu(',
      'applyMenuAction(',
      'heatColour(',
      'columnRange(',
      // every export format, and the one model they all read (export-model.ts, 2026-09-29)
      'exportTable(',
      'toXlsx(',
      'toHtml(',
      'toPlainText(',
      'toPdf(',
      'exportCsv(',
      'toEml(',
      'toCsv(',
      'drillLambda(',
      'selectionStats(',
      'writeCube(',
      'availableDimensions(',
      'new CubeEditor(',
      'new FilterEditor(',
      'new PivotPanel(',
      'new MenuView(',
    ]) {
      assert.ok(APP.includes(call), `src/app.ts never calls ${call}`);
    }
  });

  it('binds the context menu to a contextmenu event', () => {
    // The exact hole the audit found: the menu was built and tested
    // as data, and `grep -c contextmenu src/grid/grid.ts` returned 0.
    assert.ok(APP.includes("addEventListener('contextmenu'"));
  });
});
