// A query's result type, AS THE COMPILER GIVES IT
// (docs/DATACUBE_TYPED_VALUES_DESIGN_2026_09_27.md, step 1).
//
// Every plane hands DataCube a type in legend-engine's own shapes: the browser
// planner and legend-lite's `pure/v1` answer `lambdaRelationType`'s `RelationType`
// (`{columns: [{name, genericType: {rawType: {fullPath}}}]}`), and a plan carries
// `tdsColumns: [{name, type}]`. Two vocabularies reach this one reader: legend-lite's
// typer says `Integer`, `Decimal`, `DateTime`; legend-engine names a relational column
// with its precise primitive (`meta::pure::precisePrimitives::Varchar`, `Int`,
// `Numeric`, `Timestamp`). Both become the Pure type names the rest of DataCube reads.
// A name it does not know is an ERROR, never a guess: a column typed wrongly
// aggregates wrongly without a word.

import { plainType } from './types.ts';

/** One result column: its name and its Pure type, as the compiler typed it. */
export interface PlanColumn {
  readonly name: string;
  readonly type: string;
  /**
   * The model's ENUMERATION the compiler typed it with, when it is one (a saved query's
   * `Side: x|$x.side`). Its `type` is then String: what DataCube can read of it is its value's
   * name, and the source must say so first -- `->toString()` in its projection
   * (saved-queries.ts `enumsAsStrings`), without which legend-lite cannot plan it on DuckDB.
   */
  readonly enumeration?: string;
}

/** A planned query: the SQL to run, and the type of what it returns. */
export interface Plan {
  readonly sql: string;
  readonly columns: readonly PlanColumn[];
}

/**
 * A type name, in either vocabulary, as the plain Pure type DataCube reads: legend-lite's
 * lattice, generated by running it (`types.ts`); an unknown name is refused.
 */
export function pureType(name: string): string {
  return plainType(name);
}

/**
 * ENGINE DEFECT (docs/SEMANTICS_REGISTER.md S23) -- delete when legend-engine types BIT Boolean.
 *
 * legend-engine's compiler types a Database `BIT` column `precisePrimitives::TinyInt` (one case in
 * `RelationalCompilerExtension.convertTypes`, :1085), while legend-pure, the engine's own result
 * typing and its DuckDB DDL read BIT as Boolean -- and the rows ARE booleans (probed 2026-10-01:
 * the plan says TinyInt, DuckDB returns true/false). No grammar declares a BOOLEAN column, so a
 * boolean is always declared BIT. A column is therefore read as Boolean when engine's PRECISE
 * type is TinyInt and the model DataCube itself wrote declares that column BIT (`bitColumns`,
 * infer.ts): a real TINYINT column is declared TINYINT, and an aggregate over the column (count,
 * sum) is typed Integer, not TinyInt, so neither is touched. Every query DataCube builds over a
 * boolean (`== true/false`, `!=`, `in`, `isEmpty`, sort, group, count) compiles on engine over
 * TinyInt. legend-lite types BIT Boolean itself and never answers TinyInt.
 */
const ENGINE_TINYINT = 'meta::pure::precisePrimitives::TinyInt';

function typeOf(name: string, path: string, bitColumns: ReadonlySet<string>): string {
  return path === ENGINE_TINYINT && bitColumns.has(name) ? 'Boolean' : pureType(path);
}

const NO_BIT: ReadonlySet<string> = new Set();
const NONE: ReadonlySet<string> = new Set();

/** A column of `path`: an enumeration of the model is said so, any other type read as above. */
function columnOf(name: string, path: string, bitColumns: ReadonlySet<string>, enumerations: ReadonlySet<string>): PlanColumn {
  return enumerations.has(path) ? { name, type: 'String', enumeration: path } : { name, type: typeOf(name, path, bitColumns) };
}

/** legend-engine's `RelationType` JSON (`lambdaRelationType`'s answer) as columns. */
export function relationColumns(
  relationType: unknown,
  bitColumns: ReadonlySet<string> = NO_BIT,
  enumerations: ReadonlySet<string> = NONE,
): PlanColumn[] {
  const columns = (relationType as { columns?: unknown }).columns;
  if (!Array.isArray(columns)) {
    throw new Error('the relation type carries no columns');
  }
  return columns.map((c: unknown) => {
    const col = c as { name?: unknown; genericType?: { rawType?: { fullPath?: unknown } } };
    const path = col.genericType?.rawType?.fullPath;
    if (typeof col.name !== 'string' || typeof path !== 'string') {
      throw new Error(`a relation type column without a name and a type: ${JSON.stringify(c)}`);
    }
    return columnOf(col.name, path, bitColumns, enumerations);
  });
}

/** A plan's `tdsColumns` (generatePlan's `resultType`) as columns. */
export function tdsColumns(plan: unknown, bitColumns: ReadonlySet<string> = NO_BIT): PlanColumn[] {
  const root = (plan as { rootExecutionNode?: { resultType?: { tdsColumns?: unknown } } })
    .rootExecutionNode;
  const cols = root?.resultType?.tdsColumns;
  if (!Array.isArray(cols)) {
    throw new Error('the plan carries no tdsColumns');
  }
  return cols.map((c: unknown) => {
    const col = c as { name?: unknown; type?: unknown };
    if (typeof col.name !== 'string' || typeof col.type !== 'string') {
      throw new Error(`a plan column without a name and a type: ${JSON.stringify(c)}`);
    }
    return { name: col.name, type: typeOf(col.name, col.type, bitColumns) };
  });
}
