// THE one reader of a column's type (docs/DATACUBE_TYPES_TO_SERVER_2026_09_27.md, T1).
//
// A column's type is the compiler's: legend-lite's plain name (`Integer`), or
// legend-engine's precise primitive by path (`meta::pure::precisePrimitives::BigInt`).
// What DataCube needs from it -- its family, its plain primitive -- is legend-lite's
// own lattice, generated by running it (`generated/lite-facts.ts`, decision D1).
// Nothing here names a type to decide what it is: a name the table does not know is
// an ERROR, never a guess, because a column read as the wrong family aggregates,
// filters and formats wrongly without a word.

import { TYPE_FACTS, type TypeFact, type TypeFamily } from './generated/lite-facts.ts';

export type { TypeFamily };

/** A reported type name's plain primitive and family; unknown names are refused. */
export function typeFact(type: string): TypeFact {
  const fact = TYPE_FACTS[type];
  if (fact === undefined) {
    throw new Error(`the compiler typed a column '${type}', which DataCube does not read`);
  }
  return fact;
}

/** The plain Pure primitive a reported type is (`meta::pure::precisePrimitives::Int` is `Integer`). */
export function plainType(type: string): string {
  return typeFact(type).plain;
}

// The predicates take `undefined`: a calculated column in an editor's draft has no type
// until it is applied and the refresh's step 0 asks the compiler. Untyped has no family --
// never a guessed one. Every column a QUERY reads is typed by then.

export function familyOf(type: string | undefined): TypeFamily | undefined {
  return type === undefined ? undefined : typeFact(type).family;
}

export function isNumeric(type: string | undefined): boolean {
  return familyOf(type) === 'numeric';
}

/** A numeric type that carries a fraction: Float, Decimal and the abstract Number. */
export function isFractional(type: string | undefined): boolean {
  return isNumeric(type) && plainType(type as string) !== 'Integer';
}

export function isTemporal(type: string | undefined): boolean {
  return familyOf(type) === 'temporal';
}

export function isBoolean(type: string | undefined): boolean {
  return familyOf(type) === 'boolean';
}

export function isVariant(type: string | undefined): boolean {
  return familyOf(type) === 'variant';
}

/** A temporal type with a time of day: DateTime (and Timestamp, which is one). */
export function hasTimeOfDay(type: string | undefined): boolean {
  return isTemporal(type) && plainType(type as string) === 'DateTime';
}

/** A time of day alone: StrictTime. */
export function isTimeOfDay(type: string | undefined): boolean {
  return isTemporal(type) && plainType(type as string) === 'StrictTime';
}

/**
 * The kind a column takes when nobody declared one (decision D3, upstream's rule):
 * every numeric column is a measure -- summed in a grouped cube -- and everything else a
 * dimension. A host or user who knows a numeric column is an identifier (an id, a year)
 * declares it a dimension.
 */
export function defaultKind(type: string | undefined): 'measure' | 'dimension' {
  return isNumeric(type) ? 'measure' : 'dimension';
}
