// Copyright 2026 Legend Contributors
// SPDX-License-Identifier: Apache-2.0

package com.legend.generators;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * THE REFERENCE LANE's REPORT (execution plan W1.1, calls first): legend-pure's own compiler, from the pinned jars,
 * against ours, call by call, over {@code core_relational}'s manifest closure. The reference dump is a cached build
 * output ({@code //tools/reference:ref_dump}); this produces our side ({@link OurResolutions}), joins
 * ({@link ReferenceJoin}) and writes the report and its examples. {@code //spec:reference_lane_report} runs it;
 * {@code //spec:update_reference_lane_test} (manual, like the lane) compares the report to the committed golden
 * {@code src/test/resources/reference-lane/core_relational.txt}, and {@code bazel run //spec:update_reference_lane}
 * re-blesses a deliberate change, with the GATES entry saying which lines moved and why (Bazel workplan P2-14).
 *
 * <p>The report pins, exactly: the coverage (functions each side typed, the bodies we FAILED, the sources our loader
 * DROPPED to make the model build -- survivorship, so losing coverage turns the lane red instead of shrinking the
 * disagreements), every bucket's count, and every disagreement class with its count. Its header names the release from
 * the oracle pins ({@code //tools:oracle-pins.env}), never a typed version.
 *
 * <pre>
 *   ReferenceLaneReport &lt;ref-resolutions.tsv&gt; &lt;oracle-pins.env&gt; &lt;output directory&gt;
 *   (writes core_relational.txt and core_relational-examples.tsv there)
 * </pre>
 */
public final class ReferenceLaneReport {

    static final String MODULE = "core_relational";

    private ReferenceLaneReport() {}

    public static void main(String[] args) throws IOException {
        if (args.length != 3) {
            throw new IllegalArgumentException(
                    "usage: ReferenceLaneReport <ref-resolutions.tsv> <oracle-pins.env> <output directory>");
        }
        Map<String, String> pins = new LinkedHashMap<>();
        for (String line : Files.readAllLines(Path.of(args[1]), StandardCharsets.UTF_8)) {
            int eq = line.indexOf('=');
            if (!line.startsWith("#") && eq > 0) {
                pins.put(line.substring(0, eq), line.substring(eq + 1));
            }
        }
        StringWriter ours = new StringWriter();
        OurResolutions.Result dump;
        try (PrintWriter w = new PrintWriter(ours)) {
            dump = OurResolutions.dump(MODULE, w);
        }
        ReferenceJoin.Result join = ReferenceJoin.join(Path.of(args[0]), ours.toString());
        Path out = Path.of(args[2]);
        Files.writeString(out.resolve(MODULE + ".txt"), report(dump, join, pin(pins, "LEGEND_PURE_RELEASE"),
                pin(pins, "LEGEND_ENGINE_RELEASE")), StandardCharsets.UTF_8);
        Files.writeString(out.resolve(MODULE + "-examples.tsv"), examples(join), StandardCharsets.UTF_8);
    }

    private static String pin(Map<String, String> pins, String key) {
        String v = pins.get(key);
        if (v == null || v.isBlank()) {
            throw new IllegalStateException("the oracle pins have no " + key);
        }
        return v;
    }

    /** The report: deterministic, sorted, no positions (they live in the examples file). */
    static String report(OurResolutions.Result dump, ReferenceJoin.Result j, String pure, String engine) {
        StringBuilder sb = new StringBuilder();
        sb.append("# The reference lane (execution plan W1.1): ").append(MODULE)
                .append("'s closure, legend-pure ").append(pure).append(" / engine ").append(engine)
                .append(" jars vs ours, call by call.\n")
                .append("# Generated by ReferenceLaneReport (//spec:reference_lane_report); every line is pinned. Positions are in its examples output.\n");
        sb.append("\n== coverage\n");
        Map<String, Integer> cov = new LinkedHashMap<>();
        cov.put("reference functions", j.refFunctions());
        cov.put("our functions", j.ourFunctions());
        cov.put("our bodies typed", dump.functions());
        cov.put("our bodies FAILED", dump.failedFunctions().size());
        cov.put("our sources DROPPED", dump.droppedSources().size());
        cov.put("functions in both", j.inBoth());
        cov.put("reference only", j.refOnly());
        cov.put("ours only", j.oursOnly());
        cov.put("reference typed, we FAILED", j.refTypedWeFailed());
        cov.forEach((k, v) -> sb.append(k).append('\t').append(v).append('\n'));
        sb.append("\n== buckets\n");
        j.buckets().forEach((k, v) -> sb.append(k).append('\t').append(v).append('\n'));
        sb.append("\n== dropped sources\n");
        dump.droppedSources().forEach(s -> sb.append(s).append('\n'));
        sb.append("\n== failed bodies\n");
        dump.failedFunctions().forEach(s -> sb.append(s).append('\n'));
        sb.append("\n== disagreement classes (kind, spelling, reference id, our id, count)\n");
        j.classes().forEach((k, n) -> sb.append(k.kind()).append('\t').append(k.spelling()).append('\t')
                .append(k.refId()).append('\t').append(k.ourId()).append('\t').append(n).append('\n'));
        return sb.toString();
    }

    static String examples(ReferenceJoin.Result j) {
        StringBuilder sb = new StringBuilder("kind\tspelling\trefId\tourId\tcount\texample\n");
        j.classes().forEach((k, n) -> sb.append(k.kind()).append('\t').append(k.spelling()).append('\t')
                .append(k.refId()).append('\t').append(k.ourId()).append('\t').append(n).append('\t')
                .append(j.examples().get(k)).append('\n'));
        return sb.toString();
    }
}
