// Writes query/src/ui/icons.ts: the icons upstream Legend Query uses (legend-art's Icon.ts, by
// react-icons name), as SVG strings -- the same paths, no React, no runtime dependency.
// react-icons is MODULE.bazel's @react_icons, the version legend-studio pins
// (packages/legend-art/package.json); //query:icons_gen runs this over it, and
// `bazel run //query:update_generated` writes the result.

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const [,, root] = process.argv;
if (!root) throw new Error('usage: icons.mjs <react-icons package dir>');

/** Query's name -> [react-icons set, react-icons name, upstream's name in legend-art/src/icon/Icon.ts]. */
const ICONS = {
  play: ['fa', 'FaPlay', 'PlayIcon'],
  plus: ['fa', 'FaPlus', 'PlusIcon'],
  plusCircle: ['fi', 'FiPlusCircle', 'PlusCircleIcon'],
  times: ['fa', 'FaTimes', 'TimesIcon'],
  trash: ['fa', 'FaTrash', 'TrashIcon'],
  caretDown: ['fa', 'FaCaretDown', 'CaretDownIcon'],
  chevronRight: ['go', 'GoChevronRight', 'ChevronRightIcon'],
  chevronDown: ['go', 'GoChevronDown', 'ChevronDownIcon'],
  compress: ['fa', 'FaCompress', 'CompressIcon'],
  expand: ['fa', 'FaExpand', 'ExpandIcon'],
  info: ['fa', 'FaInfoCircle', 'InfoCircleIcon'],
  eye: ['fa', 'FaEye', 'EyeIcon'],
  search: ['fa', 'FaSearch', 'SearchIcon'],
  cog: ['fa', 'FaCog', 'CogIcon'],
  calculator: ['fa', 'FaCalculator', 'CalculatorIcon'],
  undo: ['fa', 'FaUndo', 'UndoIcon'],
  redo: ['fa', 'FaRedo', 'RedoIcon'],
  hammer: ['fa', 'FaHammer', 'HammerIcon'],
  warning: ['fa', 'FaExclamationTriangle', 'ExclamationTriangleIcon'],
  checked: ['fa', 'FaCheckSquare', 'CheckSquareIcon'],
  unchecked: ['fa', 'FaSquare', 'EmptySquareIcon'],
  typeBoolean: ['fa', 'FaToggleOn', 'ToggleIcon'],
  typeNumber: ['fa', 'FaHashtag', 'HashtagIcon'],
  typeDate: ['fa', 'FaClock', 'ClockIcon'],
  typeString: ['md', 'MdTextFields', 'StringTypeIcon'],
  save: ['md', 'MdSave', 'SaveCurrIcon'],
  saveAs: ['md', 'MdSaveAs', 'SaveAsIcon'],
  load: ['md', 'MdManageSearch', 'ManageSearchIcon'],
  more: ['md', 'MdMoreVert', 'MoreVerticalIcon'],
  sigma: ['md', 'MdFunctions', 'SigmaIcon'],
  dropHere: ['md', 'MdVerticalAlignBottom', 'VerticalAlignBottomIcon'],
  link: ['fi', 'FiLink', 'AnchorLinkIcon'],
  menu: ['io5', 'IoMenuOutline', 'MenuIcon'],
  moon: ['io5', 'IoMoon', 'MoonIcon'],
  sun: ['io5', 'IoSunnyOutline', 'SunIcon'],
};

// SVG keeps a few attributes camelCase (viewBox); the presentation attributes are hyphenated
const kebab = (s) => (s === 'viewBox' ? s : s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`));
const attrs = (a) => Object.entries(a ?? {}).map(([k, v]) => ` ${kebab(k)}="${String(v).replace(/"/g, '&quot;')}"`).join('');
const render = (node) => `<${node.tag}${attrs(node.attr)}>${(node.child ?? []).map(render).join('')}</${node.tag}>`;

const sources = new Map();
const tree = (set, name) => {
  if (!sources.has(set)) {
    const file = join(root, set, 'index.mjs');
    if (!existsSync(file)) throw new Error(`react-icons set ${set} is not given: add it to _ICON_SETS in query/BUILD.bazel`);
    sources.set(set, readFileSync(file, 'utf8'));
  }
  const m = new RegExp(`export function ${name} \\(props\\) \\{\\s*return GenIcon\\((\\{.*?\\})\\)\\(props\\);`, 's').exec(sources.get(set));
  if (!m) throw new Error(`react-icons/${set} has no ${name}`);
  return JSON.parse(m[1]);
};

const lines = [
  '// GENERATED by query/tools/icons.mjs from react-icons 5.5.0 (MIT) -- do not edit by hand:',
  '// bazel run //query:update_generated.',
  '// The icons upstream Legend Query shows (legend-art src/icon/Icon.ts), the same SVG paths:',
  '// Font Awesome Free (fa; icons CC BY 4.0), Material Design icons (md; Apache-2.0),',
  '// GitHub Octicons (go; MIT), Feather (fi; MIT), Ionicons 5 (io5; MIT).',
  '',
  '/** Each icon as SVG markup: 1em square, painted in the current text colour (react-icons\' GenIcon defaults). */',
  'export const ICONS = {',
];
for (const [key, [set, name, upstream]] of Object.entries(ICONS)) {
  const svg = tree(set, name);
  // GenIcon's defaults, under the icon's own attributes (an outline icon sets fill="none")
  svg.attr = { stroke: 'currentColor', fill: 'currentColor', strokeWidth: '0', ...svg.attr, height: '1em', width: '1em' };
  lines.push(`  /** ${upstream} = ${name} */`, `  ${key}: '${render(svg).replace(/'/g, "\\'")}',`);
}
lines.push('} as const;', '', 'export type IconName = keyof typeof ICONS;', '');
process.stdout.write(lines.join('\n'));
